CREATE OR REPLACE VIEW DBA_USER_PRIVS 
(USERNAME, ROLENAME, PRIVILEGE) AS 
SELECT
DECODE(SA1.GRANTEE#, 1, 'PUBLIC', U1.NAME)
, SUBSTR(U2.NAME,1,20)
, SUBSTR(SPM.NAME,1,27)  
FROM SYS.SYSAUTH$ SA1
     , SYS.SYSAUTH$ SA2
     , SYS.USER$ U1
     , SYS.USER$ U2
     , SYS.SYSTEM_PRIVILEGE_MAP SPM 
WHERE SA1.GRANTEE# = U1.USER# 
  AND SA1.PRIVILEGE# = U2.USER# 
  AND U2.USER# = SA2.GRANTEE# 
  AND SA2.PRIVILEGE# = SPM.PRIVILEGE 
UNION 
SELECT U.NAME
     , NULL
     , SUBSTR(SPM.NAME,1,27) 
FROM SYS.SYSTEM_PRIVILEGE_MAP SPM
    , SYS.SYSAUTH$ SA, SYS.USER$ U 
WHERE SA.GRANTEE#=U.USER#  
  AND SA.PRIVILEGE#=SPM.PRIVILEGE 
/ 
