#!/bin/csh -f
#------------------------------------------------------------------------------
  if ( "$1" == "" ) then
    echo ""
    exit 0
  endif

  set lines = "$1"

  set check = "` echo $lines | sed 's/[0-9]//g' `"

  if ( "$check" != "" ) then
    echo ""
    exit 0
  endif

  while ( $lines > 0 )
    echo ""
    @ lines = $lines - 1
  end

#------------------------------------------------------------------------------
