#!/bin/csh -f
#------------------------------------------------------------------------------

  while ( $#argv > 0 )
    set arg = "$1"
    if ( "$arg" !~ *:* ) then
      set cmd = 'echo $'"$arg"
      set val = "`$cmd`"
      if ( "$val" != "" ) set arg = "$val"
    endif
    echo "$arg" | tr : ' ' | awk '{for(i=1;i<=NF;i++)print$i}'
    shift
  end

#------------------------------------------------------------------------------
