#!/bin/csh -f
#------------------------------------------------------------------------------

  source ~phdye/.cshrc

  rm -f $ORACLE_HOME/network/{agent/services,admin/snmp_r{w,o}}.ora

  a-start

  a-log

#------------------------------------------------------------------------------
