#!/bin/csh -f
#------------------------------------------------------------------------------

echo ""
echo "Authenticate as yangl.root to become 'oracle'"
echo ""
exec su yangl.root -c "exec su - oracle"

#------------------------------------------------------------------------------
