connect SYS/change_on_install as SYSDBA
set echo on
spool _LOGS_DIR_/CreateDBFiles.log
CREATE TABLESPACE "APPS" LOGGING DATAFILE '_DBF_APPS_' SIZE 1024M REUSE AUTOEXTEND ON NEXT  2048K MAXSIZE  8191M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "COSTING" LOGGING DATAFILE '_DBF_COSTING_' SIZE 1024M REUSE AUTOEXTEND ON NEXT  2048K MAXSIZE  8191M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "CWMLITE" LOGGING DATAFILE '_DBF_CWMLITE_' SIZE 20M REUSE AUTOEXTEND ON NEXT  640K MAXSIZE  32767M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "DRSYS" LOGGING DATAFILE '_DBF_DRSYS_' SIZE 20M REUSE AUTOEXTEND ON NEXT  640K MAXSIZE  32767M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "INDX" LOGGING DATAFILE '_DBF_INDX_' SIZE 768M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE  32767M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "ODM" LOGGING DATAFILE '_DBF_ODM_' SIZE 20M REUSE AUTOEXTEND ON NEXT  640K MAXSIZE  32767M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TEMPORARY TABLESPACE "TEMP2" TEMPFILE '_DBF_TEMP2_' SIZE 1024M REUSE AUTOEXTEND ON NEXT  512K MAXSIZE  9216M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1024K;
CREATE TABLESPACE "TOOLS" LOGGING DATAFILE '_DBF_TOOLS_' SIZE 10M REUSE AUTOEXTEND ON NEXT  320K MAXSIZE  32767M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "USERS" LOGGING DATAFILE '_DBF_USERS_' SIZE 25M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE  32767M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE TABLESPACE "XDB" LOGGING DATAFILE '_DBF_XDB_' SIZE 38M REUSE AUTOEXTEND ON NEXT  640K MAXSIZE  32767M BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;
spool off
exit;
