connect SYS/change_on_install as SYSDBA
set echo on
spool _LOGS_DIR_/CreateDB.log
startup nomount pfile="_INIT_ORA_";
CREATE DATABASE _DB_SID_
MAXINSTANCES 1
MAXLOGHISTORY 1
MAXLOGFILES 5
MAXLOGMEMBERS 5
MAXDATAFILES 100
DATAFILE '_DBF_SYSTEM_' SIZE 400M REUSE AUTOEXTEND ON NEXT  10240K MAXSIZE  32767M
EXTENT MANAGEMENT LOCAL
DEFAULT TEMPORARY TABLESPACE TEMP TEMPFILE '_DBF_TEMP_' SIZE 41M REUSE AUTOEXTEND ON NEXT  640K MAXSIZE  32767M
UNDO TABLESPACE "UNDOTBS1" DATAFILE '_DBF_UNDO_' SIZE 200M REUSE AUTOEXTEND ON NEXT  5120K MAXSIZE  32767M
CHARACTER SET WE8ISO8859P1
NATIONAL CHARACTER SET AL16UTF16
LOGFILE GROUP 1 ('_REDO_LOG_1_') SIZE 102400K,
GROUP 2 ('_REDO_LOG_2_') SIZE 102400K,
GROUP 3 ('_REDO_LOG_3_') SIZE 102400K;
spool off
exit;
