PROMPT Create tables in hostdb schema

REM Either login as a user has DBA role or as user hostdb
connect / as sysdba

CREATE TABLE HOSTDB.ACCOUNTS 
(
ID NUMBER(6) 
	constraint ACCT_ID_NN NOT NULL
, FLAG CHAR(1)
, PROJECT VARCHAR2(8)
, TASK VARCHAR2(8)
, AWARD VARCHAR2(8)
, FUNDING VARCHAR2(6)
, FUNCTION VARCHAR2(3)
, ACTIVITY VARCHAR2(3)
, ORG VARCHAR2(6)
, ENTITY VARCHAR2(2)
, EXPIRES DATE
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(50)
, LAST_UPDATE_DATE DATE
, LAST_UPDATED_BY VARCHAR2(50)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 50K NEXT 128K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACCOUNT_FLAGS 
(
FLAG CHAR(1) 
	CONSTRAINT ACCTFLAG_FLAG_NN NOT NULL
, DESCRIPTION VARCHAR2(10) 
	CONSTRAINT ACCTFLAG_DESC_NN NOT NULL
, INVALID CHAR(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACCOUNT_SUBS 
(
PRINC VARCHAR2(8)
, SRC_ACCOUNT NUMBER(6)
, DST_ACCOUNT NUMBER(6)
    )  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACL 
(
PRINC VARCHAR2(8) 
	CONSTRAINT ACL_PRINC_NN NOT NULL
, ITEM VARCHAR2(10) 
	CONSTRAINT ACL_ITEM_NN NOT NULL
, RIGHT CHAR(1) 
	CONSTRAINT ACL_RIGHT_NN NOT NULL
, ACCOUNT NUMBER(6)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64 NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACL_GL_ORGS 
(
EMPLOYEE_ID NUMBER
, GL_ORG_NUMBER VARCHAR2(10)
, START_DATE_ACTIVE DATE
, END_DATE_ACTIVE DATE)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACL_PROJECTS
(
EMPLOYEE_ID NUMBER
, PROJECT_ID NUMBER
, START_DATE_ACTIVE DATE
, END_DATE_ACTIVE DATE
, PROJECT_ROLE VARCHAR2(80)
) 
    TABLESPACE APPS PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACL_PROJECTS_EXTRA 
(
ID VARCHAR2(10) 
	CONSTRAINT ACLPRJEXTRA_ID_NN NOT NULL
, USER_NAME VARCHAR2(10) 
	CONSTRAINT ACLPRJEXTRA_UNAME_NN NOT NULL
, EMPLOYEE_ID NUMBER
, PROJECT_ID NUMBER)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/
COMMENT ON TABLE "HOSTDB"."ACL_PROJECTS_EXTRA" IS 'more 
    accessible accounts 
    for some users';
COMMENT ON COLUMN "HOSTDB"."ACL_PROJECTS_EXTRA"."ID" IS 'unique 
    id';
COMMENT ON COLUMN "HOSTDB"."ACL_PROJECTS_EXTRA"."USER_NAME" IS 
    'andrew user name as in acl_users';
COMMENT ON COLUMN "HOSTDB"."ACL_PROJECTS_EXTRA"."EMPLOYEE_ID" IS
    'hostdb.pta_status, not required';
COMMENT ON COLUMN "HOSTDB"."ACL_PROJECTS_EXTRA"."PROJECT_ID" IS 
    'hostdb.pta_status';

CREATE TABLE HOSTDB.ACL_RIGHTS 
(
RIGHT CHAR(1) NOT NULL
, DESCRIPTION VARCHAR2(30) NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACL_USERS 
(
EMPLOYEE_ID NUMBER
, EMPLOYEE_NUMBER VARCHAR2(30)
, USER_ID NUMBER
, USER_NAME VARCHAR2(100)
, FULL_NAME VARCHAR2(240)
, FIRST_NAME VARCHAR2(20)
, MIDDLE_NAMES VARCHAR2(60)
, LAST_NAME VARCHAR2(40))  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 256K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACL_WEB 
(
ANDREW_USRNAME VARCHAR2(100) 
	CONSTRAINT ACLWEB_ADNREWUNAME_NN NOT NULL
, RIGHT CHAR(1) NOT NULL)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 128K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACL_WEB_USERMACH 
(
EMPLOYEE_ID NUMBER
, ANDREW_ID VARCHAR2(100)
, FIRST_NAME VARCHAR2(40)
, MIDDLE_NAMES VARCHAR2(60)
, LAST_NAME VARCHAR2(40))  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 128K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACL_WEB_USRSUB 
(
ANDREW_USR VARCHAR2(100) 
	CONSTRAINT ACLWEBUSERSUB_ANDREWU_NN NOT NULL
, ACTING_AS VARCHAR2(100) 
	CONSTRAINT ACLWEBUSERSUB_ACTINGAS_NN NOT NULL) 
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64 MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACTIVITIES 
(
CODE VARCHAR2(3) 
	CONSTRAINT ACTIVITIES_CODE_NN NOT NULL
, DESCRIPTION VARCHAR2(85)
, COMPOSITE CHAR(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ACTIVITY_MAP 
(
ACTIVITY VARCHAR2(3) 
	CONSTRAINT ACTIVITYMAP_ACT_NN NOT NULL
, CATEGORY VARCHAR2(35)
, COMMENTS VARCHAR2(80))  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ALIASES 
(
ALIAS VARCHAR2(40) 
	CONSTRAINT ALIASES_ALIAS_NN NOT NULL
, GRP VARCHAR2(10) 
	CONSTRAINT ALIASES_GRP_NN NOT NULL
, HOSTNAME VARCHAR2(40)
, EXPIRES DATE
)  
    TABLESPACE "APPS" PCTFREE 5 PCTUSED 60 INITRANS 2 MAXTRANS 
    255 
    STORAGE ( INITIAL 256K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ASSETNO_HISTORY 
(
ASSETNO VARCHAR2(9) 
	CONSTRAINT ASSETNOHIST_ASSETNO_NN NOT NULL
, OLDASSETNO VARCHAR2(9) 
	CONSTRAINT ASSETNOHIST_OLDASSETNO_NN NOT NULL
, ASOF DATE 
	CONSTRAINT ASSETNOHIST_ASOF_NN NOT NULL)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.ATTRS
(
CODE VARCHAR2(3) 
	CONSTRAINT ATTRS_CODE_NN NOT NULL
, DESCRIPTION VARCHAR2(30) 
	CONSTRAINT ATTRS_DESC_NN NOT NULL
, ALLOWED VARCHAR2(3) 
	CONSTRAINT ATTRS_ALLOWED_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ATTR_SENSES 
(
SENSE CHAR(1) 
	CONSTRAINT ATTRSENSE_SENSE_NN NOT NULL
, PREFIX VARCHAR2(2)
, DESCRIPTION VARCHAR2(20) 
	CONSTRAINT ATTRSENSE_DESC_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.BACKUP 
(
ASSETNO VARCHAR2(9) 
	CONSTRAINT BACKUP_ASSETNO_NN NOT NULL
, SERVER VARCHAR2(3)
, STATUS VARCHAR2(2) 
	CONSTRAINT BACKUP_STATUS_NN NOT NULL
, NOTES VARCHAR2(40)
, HISTORY VARCHAR2(200)
, ACTIVATOR VARCHAR2(25)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.BACKUP_REPORT 
(
HOSTNAME VARCHAR2(40) 
	CONSTRAINT BACKUPRPT_HOSTNAME_NN NOT NULL
, PURGE CHAR(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


REM CREATE TABLE HOSTDB.BLDGS 
REM (
REM CODE VARCHAR2(3) 
	REM CONSTRAINT BLDGS_CODE_NN NOT NULL
REM , NAME VARCHAR2(45) 
	REM CONSTRAINT BLDGS_NAME_NN NOT NULL
REM , ADDRESS VARCHAR2(45)
REM , ABBREV VARCHAR2(8)
REM )  
    REM TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    REM 255 
    REM STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    REM 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    REM LOGGING 
REM /
REM Change it to Index Organized Table (IOT)
CREATE TABLE "BLDGS" 
	("CODE" VARCHAR2(3) 
		CONSTRAINT BLDGS_CODE_NN NOT NULL
	, "NAME" VARCHAR2(45) 
		CONSTRAINT BLDGS_NAME_NN NOT NULL
	, "ADDRESS" VARCHAR2(45)
	, "ABBREV" VARCHAR2(8)
	,CONSTRAINT BLDGS_PK PRIMARY KEY ("CODE")
	) 
	ORGANIZATION INDEX 
	PCTFREE 10 INITRANS 1 MAXTRANS 255 
	STORAGE(INITIAL 32768 FREELISTS 1 FREELIST GROUPS 1) 
	TABLESPACE "APPS" 
	LOGGING 
	NOCOMPRESS 
/

CREATE TABLE HOSTDB.CAPEQUIP 
(
ASSETNUM VARCHAR2(9) 
	CONSTRAINT CAPEQUIP_ASSETNUM_NN NOT NULL
, SERIALNUM VARCHAR2(20)
, BLDG VARCHAR2(3)
, FLR VARCHAR2(2)
, RM VARCHAR2(5)
, SUFFIX VARCHAR2(6)
, QUAL CHAR(1) 
	CONSTRAINT CAPEQUIP_QUAL_NN NOT NULL
, PONUM VARCHAR2(9)
, LINENUM NUMBER(10)
, MANUF VARCHAR2(15)
, DESCRIPTION VARCHAR2(60)
, LOCDATE DATE
, USELEVEL FLOAT(126)
, VERIFIED DATE
, DEPT VARCHAR2(5)
, PRINC VARCHAR2(8)
, WARRANTY_EXPIRE DATE
, WARRANTY_INFO VARCHAR2(80)
, IROWID NUMBER(8)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 2M NEXT 128K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CATEGORIES 
(
NAME VARCHAR2(35) 
	CONSTRAINT CATEGORIES_NAME_NN NOT NULL
, DESCRIPTION VARCHAR2(70) 
	CONSTRAINT CATEGORIES_DESC_NN NOT NULL
, FLAGS VARCHAR2(3)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CATEGORY_MACRO 
(
MACRO VARCHAR2(35) 
	CONSTRAINT CATMACRO_MACRO_NN NOT NULL
, CATEGORY VARCHAR2(35) 
	CONSTRAINT CATMACRO_CAT_NN NOT NULL
, UNITS NUMBER(6)
, WT NUMBER)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CATEGORY_MAP 
(
TYPE VARCHAR2(1) 
	CONSTRAINT CATMAP_TYPE_NN NOT NULL
, SUBTYPE VARCHAR2(3) 
	CONSTRAINT CATMAP_SUBTYPE_NN NOT NULL
, OS VARCHAR2(10)
, GENERIC VARCHAR2(11)
, OTHER VARCHAR2(10)
, CAT VARCHAR2(1)
, NOS VARCHAR2(10)
, NGENERIC VARCHAR2(11)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CATEGORY_SUP 
(
CAT VARCHAR2(35) 
	CONSTRAINT CATSUP_CAT_NN NOT NULL
, PRINC VARCHAR2(8) 
	CONSTRAINT CATSUP_PRINC_NN NOT NULL
, PRI NUMBER(2) 
	CONSTRAINT CATSUP_PRI_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CENTER 
(
CENTER VARCHAR2(7) 
	CONSTRAINT CENTER_CENTER_NN NOT NULL
, DEPT VARCHAR2(5) 
	CONSTRAINT CENTER_DEPT_NN NOT NULL
, TITLE VARCHAR2(125)
, SPONSOR VARCHAR2(50)
, PILIST VARCHAR2(80)
, EXPIRE DATE
, STMTLIST VARCHAR2(30)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CENTERS 
(
FUNDING VARCHAR2(6)
, FUNCTION VARCHAR2(3)
, ACTIVITY VARCHAR2(3)
, ORG VARCHAR2(6)
, ENTITY VARCHAR2(2)
, PROJECT VARCHAR2(8)
, TASK VARCHAR2(8)
, AWARD VARCHAR2(8)
, CENTER VARCHAR2(7) 
	CONSTRAINT CENTERS_CENTER_NN NOT NULL
, CLOSED CHAR(1)
, ACCOUNT NUMBER(6)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 128K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CENTER_COST 
(
CENTER VARCHAR2(7) 
	CONSTRAINT CENTERCOST_CENTER_NN NOT NULL
, ASOF DATE 
	CONSTRAINT CENTERCOST_ASOF_NN NOT NULL
, UNTIL DATE 
	CONSTRAINT CENTERCOST_UNTIL_NN NOT NULL
, AMOUNT NUMBER(8) 
	CONSTRAINT CENTERCOST_AMOUNT_NN NOT NULL
, NOTES VARCHAR2(130) 
	CONSTRAINT CENTERCOST_NOTES_NN NOT NULL
, SUPERVISOR VARCHAR2(8)
, PROJECT VARCHAR2(30)
, PCT NUMBER(5) 
	CONSTRAINT CENTERCOST_PCT_NN NOT NULL
, CATEGORY VARCHAR2(70) 
	CONSTRAINT CENTERCOST_CAT_NN NOT NULL
, CHARGE NUMBER(5)
) TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CENTER_MGRS 
(
CENTER VARCHAR2(7) 
	CONSTRAINT CENTERMGRS_CENTER_NN NOT NULL
, PRINC VARCHAR2(8) 
	CONSTRAINT CENTERMGRS_PRINC_NN NOT NULL
, EMAIL VARCHAR2(50)
, FLAGS VARCHAR2(4)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CENTER_SUBS 
(
PRINC VARCHAR2(8)
, SRC_CENTER VARCHAR2(7)
, DST_CENTER VARCHAR2(7)
, KIND CHAR(1)
, PCT NUMBER(5, 2)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CHARGE_CAT 
(
CODE CHAR(20) 
	CONSTRAINT CHGCAT_CODE_NN NOT NULL
, DESCRIPTION CHAR(70) 
	CONSTRAINT CHGCAT_DESC_NN NOT NULL
, ATTR CHAR(3) 
	CONSTRAINT CHGCAT_ATTR_NN NOT NULL)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CHARGE_SOURCES 
(
KIND VARCHAR2(3) 
	CONSTRAINT CHGSRC_KIND_NN NOT NULL
, DESCRIPTION VARCHAR2(70) 
	CONSTRAINT CHGSRC_DESC_NN NOT NULL
, ATTR VARCHAR2(4) 
	CONSTRAINT CHGSRC_ATTR_NN NOT NULL
, PRI NUMBER(3) 
	CONSTRAINT CHGSRC_PRI_NN NOT NULL
, ORG VARCHAR2(6)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CNOA_BAD 
(
ASSETNO VARCHAR2(9)
, PRI NUMBER(6))  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CNOA_TEST 
(
CONTEXT VARCHAR2(10)
, SAMPLE VARCHAR2(50))  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CONNECTION 
(
OUTLETID VARCHAR2(30)
, CLOC VARCHAR2(10)
, NCONN VARCHAR2(10)
, ASSETNO VARCHAR2(9) 
	CONSTRAINT CONNECTION_ASSETNO_NN NOT NULL
, MOD_DATE DATE
, BLDG VARCHAR2(3)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CONNECTIONS 
(
BLDG VARCHAR2(3)
, RM VARCHAR2(5)
, SUFFIX VARCHAR2(6)
, OUTLETID VARCHAR2(30)
, CONN NUMBER(5) 
	CONSTRAINT CONNECTIONS_CONN_NN NOT NULL
, SWITCH VARCHAR2(20)
, PORT VARCHAR2(6)
, VLAN VARCHAR2(8)
, COMMENTS VARCHAR2(30)
, BOX VARCHAR2(3)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.COST 
(
SERVICE_ID NUMBER(3) 
	CONSTRAINT COST_SVCID_NN NOT NULL
, PERIOD_BEGIN DATE 
	CONSTRAINT COST_PERIODBEGIN_NN NOT NULL
, PERIOD_END DATE
, AMOUNT NUMBER(7, 2) 
	CONSTRAINT COST_AMOUNT_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.CPUTYPES 
(
NAME VARCHAR2(10) 
	CONSTRAINT CPUTYPES_NAME_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.DEPRECIATION 
(
OBJCODE VARCHAR2(5) 
	CONSTRAINT DEPRECIATION_OBJCODE_NN NOT NULL
, TRANS_DATE DATE 
	CONSTRAINT DEPRECIATION_TRANSDATE_NN NOT NULL
, COST NUMBER(9, 2) 
	CONSTRAINT DEPRECIATION_COST_NN NOT NULL
, AMOUNT NUMBER(9, 2) 
	CONSTRAINT DEPRECIATION_AMOUNT_NN NOT NULL
, AMOUNT_NEXT NUMBER(9, 2) 
	CONSTRAINT DEPRECIATION_AMOUNTNEXT_NN NOT NULL
, LEFT NUMBER(2) 
	CONSTRAINT DEPRECIATION_LEFT_NN NOT NULL
, LEFT_NEXT NUMBER(2) 
	CONSTRAINT DEPRECIATION_LEFTNEXT_NN NOT NULL
, DESCRIPTION VARCHAR2(50) 
	CONSTRAINT DEPRECIATION_DESC_NN NOT NULL
, TAG VARCHAR2(1)
, YEARS NUMBER(2)
, POST_DATE DATE 
	CONSTRAINT DEPRECIATION_POSTDATE_NN NOT NULL
, CATEGORY VARCHAR2(35) 
	CONSTRAINT DEPRECIATION_CAT_NN NOT NULL
, NOTES VARCHAR2(50) 
	CONSTRAINT DEPRECIATION_NOTES_NN NOT NULL
, AMOUNT_DEPREC NUMBER(9, 2) 
	CONSTRAINT DEPRECIATION_AMOUNTDEPREC_NN NOT NULL
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.DEPRECIATION_RATE 
(
ID NUMBER 
	CONSTRAINT DEPRECRATE_ID_NN NOT NULL
, PERIOD_BEGIN DATE 
	CONSTRAINT DEPRECRATE_PERIODBEGIN_NN NOT NULL
, PERIOD_END DATE
, OBJCODE VARCHAR2(5) 
	CONSTRAINT DEPRECRATE_OBJCODE_NN NOT NULL
, ACCOUNT_DR NUMBER(6) 
	CONSTRAINT DEPRECRATE_ACCTDR_NN NOT NULL
, ACCOUNT_CR NUMBER(6) 
	CONSTRAINT DEPRECRATE_ACCT_CR_NN NOT NULL
, DESCRIPTION VARCHAR2(50) 
	CONSTRAINT DEPRECRATE_DESC_NN NOT NULL
, AMOUNT_DEPREC NUMBER(9, 2) 
	CONSTRAINT DEPRECRATE_AMTDEPREC_NN NOT NULL
, NOTES VARCHAR2(50)
, CATEGORY VARCHAR2(35)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.DEPTS 
(
NUMB VARCHAR2(5) 
	CONSTRAINT DEPTS_NUMB_NN NOT NULL
, NAME VARCHAR2(40) 
	CONSTRAINT DEPTS_NAME_NN NOT NULL
, ABBREV VARCHAR2(8) 
	CONSTRAINT DEPTS_ABBREV_NN NOT NULL
, CMU CHAR(1)
, SCS CHAR(1)
, OURS CHAR(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.DHCP_POOLS 
(
NAME VARCHAR2(7) 
	CONSTRAINT DHCPPOOLS_NAME_NN NOT NULL
, DESCRIPTION VARCHAR2(30)
)  
    TABLESPACE "APPS" PCTFREE 5 PCTUSED 60 INITRANS 2 MAXTRANS 
    255 
    STORAGE ( INITIAL 4 NEXT 4K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.DIST 
(
DIST NUMBER(6) 
	CONSTRAINT DIST_DIST_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT DIST_ACCT_NN NOT NULL
, PCT NUMBER(6, 3) 
	CONSTRAINT DIST_PCT_NN NOT NULL
, TPCT NUMBER(6, 3) 
	CONSTRAINT DIST_TPCT_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 128K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.DISTS 
(
ID NUMBER(6) 
	CONSTRAINT DISTS_ID_NN NOT NULL
,CONSTRAINT DISTS_PK PRIMARY KEY ("ID")
)  
	ORGANIZATION INDEX 
	PCTFREE 10 INITRANS 1 MAXTRANS 255 
	STORAGE(INITIAL 32K NEXT 32K FREELISTS 1 FREELIST GROUPS 1) 
	TABLESPACE "APPS" 
	LOGGING 
	NOCOMPRESS 
/


CREATE TABLE HOSTDB.DIST_NAMES 
(
DIST NUMBER(6) 
	constraint DNM_DIST_NN NOT NULL
, NAME VARCHAR2(30) 
	constraint DNM_NAME_NN NOT NULL
, SUBNAME VARCHAR2(12) 
	constraint DNM_SUBNAME_NN NOT NULL
, USER_ONLY  CHAR(1)
, SRC VARCHAR2(3) 
	constraint DNM_SRC_NN NOT NULL
, PCT NUMBER(5, 2)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 256K NEXT 256K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.DIST_NAMES_X 
(
DIST NUMBER(6) 
	constraint DNMX_DIST_NN NOT NULL
, NAME VARCHAR2(30) 
	constraint DNMX_NAME_NN NOT NULL
, SUBNAME VARCHAR2(12) 
	constraint DNMX_SUBNAME_NN NOT NULL
, USER_ONLY  CHAR(1)
, SRC VARCHAR2(3) 
	constraint DNMX_SRC_NN NOT NULL
, PCT NUMBER(5, 2)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 512K NEXT 256K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.EMP 
(
EMP_NAME VARCHAR2(50) 
	CONSTRAINT EMP_EMPNAME_NN NOT NULL
, FIRST VARCHAR2(50)
, MIDDLE VARCHAR2(50)
, LAST VARCHAR2(50)
, SSN NUMBER(9)
, EMP_NUM NUMBER(7)
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(30)
, LAST_UPDATE DATE
, LAST_UPDATE_BY VARCHAR2(30)
, ANDREW_ID VARCHAR2(100))  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 512K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.EXCEPTIONS 
(
ROW_ID ROWID
, OWNER VARCHAR2(30)
, TABLE_NAME VARCHAR2(30)
,  CONSTRAINT VARCHAR2(30)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 128K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.EXPENSE 
(
POST_DATE DATE 
	CONSTRAINT EXPENSE_POSTDATE_NN NOT NULL
, AMOUNT NUMBER(9, 2) 
	CONSTRAINT EXPENSE_AMOUNT_NN NOT NULL
, OBJCODE VARCHAR2(5) 
	CONSTRAINT EXPENSE_OBJCODE_NN NOT NULL
, DESCRIPTION VARCHAR2(100) 
	CONSTRAINT EXPENSE_DESC_NN NOT NULL
, CATEGORY VARCHAR2(35) 
	CONSTRAINT EXPENSE_CAT_NN NOT NULL
, CATBYPRINC VARCHAR2(8) 
	CONSTRAINT EXPENSE_CATBYPRINC_NN NOT NULL
, JOURNAL NUMBER(5) 
	CONSTRAINT EXPENSE_JOURNAL_NN NOT NULL
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 32K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.EXPENSES 
(
OBJECT VARCHAR2(5) 
	CONSTRAINT EXPENSES_OBJECT_NN NOT NULL
, FUNDING VARCHAR2(6) 
	CONSTRAINT EXPENSES_FUNDING_NN NOT NULL
, FUNCTION VARCHAR2(3) 
	CONSTRAINT EXPENSES_FUNCTION_NN NOT NULL
, ACTIVITY VARCHAR2(3) 
	CONSTRAINT EXPENSES_ACT_NN NOT NULL
, ORG VARCHAR2(6) 
	CONSTRAINT EXPENSES_ORG_NN NOT NULL
, ENTITY VARCHAR2(2) 
	CONSTRAINT EXPENSES_ENT_NN NOT NULL
, TRANS_DATE DATE 
	CONSTRAINT EXPENSES_TRANSDATE_NN NOT NULL
, DESCRIPTION VARCHAR2(256)
, DEBIT NUMBER
, CREDIT NUMBER
, CATEGORY VARCHAR2(35)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 128K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.FAILED_ACCOUNTS 
(
JOURNAL NUMBER(5) 
	CONSTRAINT FAILEDACCTS_JOURNAL_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT FAILEDACCTS_ACCT_NN NOT NULL
, DESCRIPTION VARCHAR2(80) 
	CONSTRAINT FAILEDACCTS_DESC_NN NOT NULL
, FAILED_DATE DATE
, CREATED_BY VARCHAR2(50)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.FAILED_JE_RPT 
(
POST_DATE DATE
, CHRG NUMBER
, PCT NUMBER(5, 2)
, AMT NUMBER
, CHARGE_SOURCE VARCHAR2(70)
, OS VARCHAR2(10)
, NAME VARCHAR2(40)
, MACH_USER VARCHAR2(50)
, ACCOUNT_ID NUMBER(6)
, PROJECT VARCHAR2(8)
, TASK VARCHAR2(8)
, AWARD VARCHAR2(8)
, FUND VARCHAR2(6)
, FUNC VARCHAR2(3)
, ACT VARCHAR2(3)
, ORG VARCHAR2(6)
, ENT VARCHAR2(2)
, STATUS VARCHAR2(80)
, PROJ_COMPLETION_DATE VARCHAR2(25)
, PROJ_CLOSED_DATE DATE
, TASK_COMPLETION_DATE DATE
, AWARD_END_DATE_ACTIVE DATE
, AWARD_CLOSED_DATE DATE
, PROJ_STATUS_CODE VARCHAR2(30)
, TASK_CHARGE_FLAG VARCHAR2(1)
, TASK_BILL_FLAG VARCHAR2(1)
, PRJ_SPONSOR VARCHAR2(50)
, PRINC VARCHAR2(8)
, PROJ_START_DATE DATE
, AWARD_START_DATE_ACTIVE DATE
, AWARD_STATUS VARCHAR2(30)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.FAILED_JE_TEMP 
(
POST_DATE DATE NOT NULL,
    "CHRG" NUMBER, "PCT" NUMBER(5, 2) NOT NULL, "AMT" NUMBER, "CHARGE_SOURCE" 
    VARCHAR2(70) NOT NULL, "OS" VARCHAR2(10), "NAME" 
    VARCHAR2(40) NOT NULL, "MACH_USER" VARCHAR2(50) NOT NULL, "ACCOUNT_ID" 
    NUMBER(6), "PROJECT" VARCHAR2(8), "TASK" VARCHAR2(8), "AWARD" 
    VARCHAR2(8), "FUND" VARCHAR2(6), "FUNC" VARCHAR2(3), "ACT" 
    VARCHAR2(3), "ORG" VARCHAR2(6), "ENT" VARCHAR2(2), "STATUS" 
    VARCHAR2(80) NOT NULL, "PROJ_COMPLETION_DATE" VARCHAR2(25), "PROJ_CLOSED_DATE" 
    DATE, "TASK_COMPLETION_DATE" DATE, "AWARD_END_DATE_ACTIVE" 
    DATE, "AWARD_CLOSED_DATE" DATE, "PROJ_STATUS_CODE" 
    VARCHAR2(30), "TASK_CHARGE_FLAG" VARCHAR2(1), "TASK_BILL_FLAG" 
    VARCHAR2(1), "PRJ_SPONSOR" VARCHAR2(50))  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.GENERICS 
(
NAME VARCHAR2(11) 
	CONSTRAINT GENERICS_NAME_NN NOT NULL
, NO_NET CHAR(1)
, NO_HARDWARE CHAR(1)
, NOT_OURS CHAR(1)
, CONSTRAINT GENERICS_PK PRIMARY KEY ("NAME")
)  
	ORGANIZATION INDEX 
	PCTFREE 10 INITRANS 1 MAXTRANS 255 
	STORAGE(INITIAL 32K FREELISTS 1 FREELIST GROUPS 1) 
	TABLESPACE "APPS" 
	LOGGING 
	NOCOMPRESS 
/

CREATE TABLE HOSTDB.HOSTNAME_CONTEXTS 
(
NAME VARCHAR2(10) 
	CONSTRAINT HOSTNAMECTXS_NAME_NN NOT NULL
, IS_NUMERIC CHAR(1)
, MAX_LENGTH NUMBER(5)
, MIN_PART_LENGTH NUMBER(5)
, MAX_PART_LENGTH NUMBER(5)
, MIN_NUM_PARTS NUMBER(5)
, MAX_NUM_PARTS NUMBER(5)
, SEPARATOR CHAR(1) 
	CONSTRAINT HOSTNAMECTXS_SEPERATOR_NN NOT NULL
, VALID_SEP VARCHAR2(255) 
	CONSTRAINT HOSTNAMECTXS_VALIDSEP_NN NOT NULL
, VALID_START VARCHAR2(255)
, VALID_END VARCHAR2(255)
, VALID_CHARS VARCHAR2(255)
, FORCE_CASE CHAR(1)
, PAD_DIRECTION CHAR(1)
, PAD_LENGTH NUMBER(5)
, PAD_CHAR CHAR(1)
, MIN_PART NUMBER(10)
, MAX_PART NUMBER(10)
, PART_BASE NUMBER(10)
, SPLIT_DIRECTION CHAR(1)
, SPLIT_WIDTH NUMBER(5)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 128K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.HOST_ADJUST_CHARGE 
(
HR_ID NUMBER(6) 
	CONSTRAINT HOSTADJCHG_HRID_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT HOSTADJCHG_PCT_NN NOT NULL
, HPCT NUMBER(5, 2) 
	CONSTRAINT HOSTADJCHG_HPCT_NN NOT NULL
, CHARGE NUMBER(6, 2) 
	CONSTRAINT HOSTADJCHG_CHG_NN NOT NULL
, AMOUNT NUMBER(6, 2) 
	CONSTRAINT HOSTADJCHG_AMT_NN NOT NULL
, TRANS_DATE DATE 
	CONSTRAINT HOSTADJCHG_TRANSDATE_NN NOT NULL
, SERVICE_ID NUMBER(3) 
	CONSTRAINT HOSTADJCHG_SVCID_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT HOSTADJCHG_ACCT_NN NOT NULL
, JOURNAL NUMBER(3)
, NOTES VARCHAR2(50)
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(50)
, LAST_UPDATE_DATE DATE
, LAST_UPDATED_BY VARCHAR2(50)
, HOLD_FLAG VARCHAR2(1)
, LIMBO_FLAG VARCHAR2(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.HOST_ATTR 
(
HOSTNAME VARCHAR2(40) 
	CONSTRAINT HOSTATTR_HOSTNAME_NN NOT NULL
, ATTR VARCHAR2(3) 
	CONSTRAINT HOSTATTR_ATTR_NN NOT NULL
, SENSE CHAR(1) 
	CONSTRAINT HOSTATTR_SENSE_NN NOT NULL
, NOTES VARCHAR2(30)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.HOSTSTAB 
(
HOSTNAME VARCHAR2(40) 
	constraint HOSTSTAB_HN_NN NOT NULL
, OS VARCHAR2(10)
, OSVERS VARCHAR2(10)
, IPADDRESS VARCHAR2(30)
, ASSETNO VARCHAR2(9) 
	constraint HOSTSTAB_ASSETNO_NN NOT NULL
, PROTOCOL VARCHAR2(3) 
	constraint HOSTSTAB_PRTCL_NN NOT NULL
, PRI NUMBER(6) 
	constraint HOSTSTAB_PRI_NN NOT NULL
, TTL NUMBER(6)
, PCT_USE NUMBER(5)
, IROWID NUMBER(6)
, OPRI NUMBER(6)
, CONN NUMBER(5)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 2M NEXT 128K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.HOST_CHARGED 
(
HR_ID NUMBER(6) 
	CONSTRAINT HC_HRID_NN NOT NULL
,JOURNAL NUMBER(5) 
	CONSTRAINT HC_JNL_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT HC_PCT_NN NOT NULL
, HPCT NUMBER(5, 2)
, CHARGE NUMBER(6, 2) 
	CONSTRAINT HC_CHG_NN NOT NULL
, AMOUNT NUMBER(6, 2) 
	CONSTRAINT HC_AMT_NN NOT NULL
, TRANS_DATE DATE 
	CONSTRAINT HC_TRANSDATE_NN NOT NULL
, SERVICE_ID NUMBER(3) 
	CONSTRAINT HC_SVCID_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT HC_ACCT_NN NOT NULL
, ACCOUNT_FLAG CHAR(1)
, NOTES VARCHAR2(50)
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(50)
, LAST_UPDATE_DATE DATE
, LAST_UPDATED_BY VARCHAR2(50)
)  
    TABLESPACE "COSTING_LG" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 4M NEXT 256K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.HOST_RECORDED 
(
ID NUMBER(6) 
	CONSTRAINT HR_ID_NN NOT NULL
, HOSTNAME VARCHAR2(40) 
	CONSTRAINT HR_HOSTNAME_NN NOT NULL
, ASSETNO VARCHAR2(9) 
	CONSTRAINT HR_ASSETNO_NN NOT NULL
, CPU VARCHAR2(30) 
	CONSTRAINT HR_CPU_NN NOT NULL
, QUAL VARCHAR2(1)
, CHARGE_SRC VARCHAR2(3)
, OS VARCHAR2(10)
, LOCATION VARCHAR2(30)
, PROJECT VARCHAR2(30)
, SUBPROJECT VARCHAR2(12)
, PRJPRINC VARCHAR2(8)
, USRPRINC VARCHAR2(8)
, PRINC VARCHAR2(8)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 512k NEXT 128K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.HOST_SERVICE 
(
ASSETNO VARCHAR2(9) 
	CONSTRAINT HOSTSVC_ASSETNO_NN NOT NULL
, PRI NUMBER(6) 
	CONSTRAINT HOSTSVC_PRI_NN NOT NULL
, SERVICE_ID NUMBER(3) 
	CONSTRAINT HOSTSVC_SVCID_NN NOT NULL
, PCT NUMBER(5, 2)
, SHARED VARCHAR2(10)
, JOURNAL NUMBER(5)
, TRANS_DATE DATE
, HR_ID NUMBER(6)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 128K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 10 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.HOST_SERVICE_CHARGE 
(
ASSETNO VARCHAR2(9) 
	CONSTRAINT HSC_ASSETNO_NN NOT NULL
, PRI NUMBER(6) 
	CONSTRAINT HSC_PRI_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT HSC_PCT_NN NOT NULL
, CHARGE NUMBER(6, 2) 
	CONSTRAINT HSC_CHG_NN NOT NULL
, AMOUNT NUMBER(6, 2) 
	CONSTRAINT HSC_AMT_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT HSC_ACCT_NN NOT NULL
, SERVICE_ID NUMBER(3) 
	CONSTRAINT HSC_SVCID_NN NOT NULL
, HR_ID NUMBER(6)
, JOURNAL NUMBER(5)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.HOST_SERVICE_MATRIX 
(
ASSETNO VARCHAR2(9) 
	CONSTRAINT HOSTSVCMATRIX_ASSETNO_NN NOT NULL
, OS VARCHAR2(32)
, PLATFORM VARCHAR2(11)
, NETWORK VARCHAR2(1)
, MACH_ROOM VARCHAR2(10)
, HARD_LABOR VARCHAR2(1)
, HARD_REPAIR VARCHAR2(1)
, SOFT_SUPPORT VARCHAR2(1)
, SOFT_LICENSING VARCHAR2(1)
, BACKUP VARCHAR2(1)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 256K NEXT 128K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ICES_LDR 
(
PRINC VARCHAR2(8) 
	CONSTRAINT ICESLDR_PRINC_NN NOT NULL
, NAME VARCHAR2(50) 
	CONSTRAINT ICESLDR_NAME_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT ICESLDR_PCT_NN NOT NULL
, PROJECT VARCHAR2(8)
, TASK VARCHAR2(8)
, AWARD VARCHAR2(8)
, FUNDING VARCHAR2(6)
, FUNCTION VARCHAR2(3)
, ACTIVITY VARCHAR2(3)
, ORG VARCHAR2(6)
, ENTITY VARCHAR2(2)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ICES_LDR_ARCHIVE (PRINC VARCHAR2(8) NOT
    NULL, "NAME" VARCHAR2(50) NOT NULL, "PCT" NUMBER(5, 2) NOT 
    NULL, "PROJECT" VARCHAR2(8), "TASK" VARCHAR2(8), "AWARD" 
    VARCHAR2(8), "FUNDING" VARCHAR2(6), "FUNCTION" VARCHAR2(3), "ACTIVITY" 
    VARCHAR2(3), "ORG" VARCHAR2(6), "ENTITY" VARCHAR2(2))  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ICES_RECORDED 
(
PERIOD_LAST DATE 
	CONSTRAINT ICESRECORDED_PERIODLAST_NN NOT NULL
, PRINC VARCHAR2(8) 
	CONSTRAINT ICESRECORDED_PRINC_NN NOT NULL
, NAME VARCHAR2(50) 
	CONSTRAINT ICESRECORDED_NAME_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT ICESRECORDED_PCT_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT ICESRECORDED_ACCT_NN NOT NULL
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.JOURNAL 
(
JOURNAL NUMBER(5) 
	CONSTRAINT JOURNAL_JNL_NN NOT NULL
, AMOUNT NUMBER(10, 2) 
	CONSTRAINT JOURNAL_AMOUNT_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT JOURNAL_ACCT_NN NOT NULL
, POST_DATE DATE 
	CONSTRAINT JOURNAL_POSTDATE_NN NOT NULL
, DESCRIPTION VARCHAR2(200) 
	CONSTRAINT JOURNAL_DESC_NN NOT NULL
, OBJCODE VARCHAR2(5) 
	CONSTRAINT JOURNAL_OBJCODE_NN NOT NULL
, TRANS_DATE DATE
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(50)
, LAST_UPDATE_DATE DATE
, LAST_UPDATED_BY VARCHAR2(50)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 256K NEXT 128K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.JOURNALS 
(
ID NUMBER(5) 
	CONSTRAINT JNLS_ID_NN NOT NULL
, POST_DATE DATE 
	CONSTRAINT JNLS_POSTDATE_NN NOT NULL
, JOURNAL_TYPE_FLAG VARCHAR2(1)
, JE_IN_PROCESS_FLAG VARCHAR2(1)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 128K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.JOURNAL_MISSED 
(
JOURNAL NUMBER(5) 
	CONSTRAINT JNLMISSED_JNL_NN NOT NULL
, AMOUNT NUMBER(10, 2) 
	CONSTRAINT JNLMISSED_AMT_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT JNLMISSED_ACCT_NN NOT NULL
, POST_DATE DATE 
	CONSTRAINT JNLMISSED_POSTDATE_NN NOT NULL
, DESCRIPTION VARCHAR2(200) 
	CONSTRAINT JNLMISSED_DESC_NN NOT NULL
, OBJCODE VARCHAR2(5) 
	CONSTRAINT JNLMISSED_OBJCODE_NN NOT NULL
, TRANS_DATE DATE
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(50)
, LAST_UPDATE_DATE DATE
, LAST_UPDATED_BY VARCHAR2(50)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.KGROUP 
(
NAME CHAR(8) 
	CONSTRAINT KGRP_NAME_NN NOT NULL
, DESCRIPTION CHAR(30) 
	CONSTRAINT KGRP_DESC_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.KGROUPS 
(
NAME VARCHAR2(8) 
	CONSTRAINT KGRPS_NAME_NN NOT NULL
, PRINCIPAL VARCHAR2(25) 
	CONSTRAINT KGRPS_PRINC_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.LABOR 
(
PRINC VARCHAR2(8)
, NAME VARCHAR2(50) 
	CONSTRAINT LABOR_NAME_NN NOT NULL
, PROJECT VARCHAR2(8)
, EXPORG VARCHAR2(60)
, EXPTYPE VARCHAR2(60)
, TASK VARCHAR2(8)
, AWARD VARCHAR2(8)
, OBJCODE VARCHAR2(5)
, FUNDING VARCHAR2(6)
, FUNCTION VARCHAR2(3)
, ACTIVITY VARCHAR2(3)
, ORG VARCHAR2(6)
, ENTITY VARCHAR2(2)
, PCT NUMBER(5, 2) 
	CONSTRAINT LABOR_PCT_NN NOT NULL
, PERIOD DATE 
	CONSTRAINT LABOR_PERIOD_NN NOT NULL
, HOME_ORG VARCHAR2(60) 
	CONSTRAINT LABOR_HOMEORG_NN NOT NULL
, APPOINTMENT NUMBER(7) 
	CONSTRAINT LABOR_EMPNO_NN NOT NULL
, RECNUM NUMBER(5) 
	CONSTRAINT LABOR_RECNUM_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.LABOR_LDR 
(
NAME VARCHAR2(50) 
	CONSTRAINT LABORLDR_NAME_NN NOT NULL
, PROJECT VARCHAR2(8)
, EXPORG VARCHAR2(60)
, EXPTYPE VARCHAR2(60)
, TASK VARCHAR2(8)
, AWARD VARCHAR2(8)
, OBJCODE VARCHAR2(5)
, FUNDING VARCHAR2(6)
, FUNCTION VARCHAR2(3)
, ACTIVITY VARCHAR2(3)
, ORG VARCHAR2(6)
, ENTITY VARCHAR2(2)
, PCT NUMBER(5, 2) 
	CONSTRAINT LABORLDR_PCT_NN NOT NULL
, PERIOD DATE 
	CONSTRAINT LABORLDR_PERIOD_NN NOT NULL
, HOME_ORG VARCHAR2(60) 
	CONSTRAINT LABORLDR_HOMEORG_NN NOT NULL
, APPOINTMENT NUMBER(7) 
	CONSTRAINT LABORLDR_EMPNO_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 256K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 10 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.LABOR_NOMATCH 
(
NAME VARCHAR2(50) 
	CONSTRAINT LABORNOMATCH_NAME_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT LABORNOMATCH_PCT_NN NOT NULL
, APPOINTMENT NUMBER(7) 
	CONSTRAINT LABORNOMATCH_EMPNO_NN NOT NULL
, PERIOD DATE 
	CONSTRAINT LABORNOMATCH_PERIOD_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/



CREATE TABLE HOSTDB.LABOR_RECORDED 
(
PERIOD_LAST DATE 
	CONSTRAINT LBRRCD_PERIODLAST_NN NOT NULL
, PRINC VARCHAR2(8)
, NAME VARCHAR2(50) 
	CONSTRAINT LBRRCD_NAME_NN NOT NULL
, EXPORG VARCHAR2(60)
, EXPTYPE VARCHAR2(60)
, OBJCODE VARCHAR2(5)
, ACCOUNT NUMBER(6) 
	CONSTRAINT LBRRCD_ACCT_NN NOT NULL
, PCT_ORIG NUMBER(5, 2) 
	CONSTRAINT LBRRCD_PCTO_NN NOT NULL
, PCT_NORM NUMBER(5, 2) 
	CONSTRAINT LBRRCD_PCTN_NN NOT NULL
, PERIOD DATE 
	CONSTRAINT LBRRCD_PERIOD_NN NOT NULL
, HOME_ORG VARCHAR2(60) 
	CONSTRAINT LBRRCD_HOMEORG_NN NOT NULL
, APPOINTMENT NUMBER(7) 
	CONSTRAINT LBRRCD_EMPNO_NN NOT NULL
, CHARGE_SRC VARCHAR2(3) 
	CONSTRAINT LBRRCD_CHARGESRC_NN NOT NULL
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 50K NEXT 9964K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.LABOR_REC_HOLD 
(
PERIOD_LAST DATE 
	CONSTRAINT LABORRECHOLD_PERIODLAST_NN NOT NULL
, PRINC VARCHAR2(8)
, NAME VARCHAR2(50) 
	CONSTRAINT LABORRECHOLD_NAME_NN NOT NULL
, EXPORG VARCHAR2(60)
, EXPTYPE VARCHAR2(60)
, OBJCODE VARCHAR2(5)
, ACCOUNT NUMBER(6) 
	CONSTRAINT LABORRECHOLD_ACCT_NN NOT NULL
, PCT_ORIG NUMBER(5, 2) 
	CONSTRAINT LABORRECHOLD_PCTORIG_NN NOT NULL
, PCT_NORM NUMBER(5, 2) 
	CONSTRAINT LABORRECHOLD_PCTNORM_NN NOT NULL
, PERIOD DATE 
	CONSTRAINT LABORRECHOLD_PERIOD_NN NOT NULL
, HOME_ORG VARCHAR2(60) 
	CONSTRAINT LABORRECHOLD_HOMEORG_NN NOT NULL
, APPOINTMENT NUMBER(7) 
	CONSTRAINT LABORRECHOLD_EMPNO_NN NOT NULL
, CHARGE_SRC VARCHAR2(3) 
	CONSTRAINT LABORRECHOLD_CHGSRC_NN NOT NULL
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.LOOKUP_CODES 
(
CODE VARCHAR2(30) 
	CONSTRAINT LOOKUPCODES_CODE_NN NOT NULL
, MEANING VARCHAR2(200) 
	CONSTRAINT LOOKUPCODES_MEANING_NN NOT NULL
, CODE_TYPE VARCHAR2(10) 
	CONSTRAINT LOOKUPCODES_CODETYPE_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING
/
COMMENT ON COLUMN "HOSTDB"."LOOKUP_CODES"."CODE_TYPE" IS 
    'Application set of codes';



CREATE TABLE HOSTDB.MACHTAB 
(
ASSETNO VARCHAR2(9) 
	CONSTRAINT MACHTAB_ASSETNO_NN NOT NULL
, CPUTYPE VARCHAR2(10) 
	CONSTRAINT MACHTAB_CPUTYPE_NN NOT NULL
, CPUMODEL VARCHAR2(20) 
	CONSTRAINT MACHTAB_CPUMODEL_NN NOT NULL
, CPUMODELEXT VARCHAR2(20)
, HOSTID VARCHAR2(20)
, PROJECT VARCHAR2(30)
, HWADDR VARCHAR2(20)
, USRPRINC VARCHAR2(8)
, PRJPRINC VARCHAR2(8)
, USAGE CHAR(1)
, IROWID CHAR(1)
, DIST NUMBER(6)
, CHARGE_BY CHAR(1)
, OPROJECT CHAR(1)
, OUSAGE CHAR(1)
, SUBPROJECT VARCHAR2(12)
, DIST_SRC VARCHAR2(3)
, MR_CLASS VARCHAR2(10)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 2M NEXT 128K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.MACH_ATTR 
(
ASSETNO VARCHAR2(9) 
	CONSTRAINT MACHATTR_ASSETNO_NN NOT NULL
, ATTR VARCHAR2(3) 
	CONSTRAINT MACHATTR_ATTR_NN NOT NULL
, SENSE CHAR(1) 
	CONSTRAINT MACHATTR_SENSE_NN NOT NULL
, NOTES VARCHAR2(30)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.MACH_CHARGE 
(
ASSETNO VARCHAR2(9) 
	CONSTRAINT MACHCHG_ASSETNO_NN NOT NULL
, CENTER VARCHAR2(7) 
	CONSTRAINT MACHCHG_CENTER_NN NOT NULL
, PROJECT VARCHAR2(30)
, SUPERVISOR VARCHAR2(8)
, PCT NUMBER(5) 
	CONSTRAINT MACHCHG_PCT_NN NOT NULL
, KIND CHAR(1)
, BILL_BGN DATE
, BILL_END DATE
, MPROJECT VARCHAR2(30)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.MACH_CONFIG 
(
ASSETNO VARCHAR2(9)
, DEVASSETNO VARCHAR2(9)
, DEVTYPE VARCHAR2(20)
, EXTERNAL VARCHAR2(3)
, DESCRIPTION VARCHAR2(70)
, COMMNTS VARCHAR2(70)
, EXT CHAR(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.MACH_EQUIV 
(
CPUTYPE VARCHAR2(10) 
	CONSTRAINT MACHEQUIV_CPUTYPE_NN NOT NULL
, CPUMODEL VARCHAR2(20) 
	CONSTRAINT MACHEQUIV_CPUMODEL_NN NOT NULL
, GENERIC VARCHAR2(11) 
	CONSTRAINT MACHEQUIV_GENERIC_NN NOT NULL
, SPECIFIC VARCHAR2(11)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.MACH_RATE 
(
CPU CHAR(11) 
	CONSTRAINT MACHRATE_CPU_NN NOT NULL
, OS CHAR(20)
, RATE FLOAT(126) 
	CONSTRAINT MACHRATE_RATE_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.MACH_THRU 
(
ASSETNO CHAR(9) 
	CONSTRAINT MACHTHRU_ASSETNO_NN NOT NULL
, ATTR CHAR(30) 
	CONSTRAINT MACHTHRU_ATTR_NN NOT NULL
, ASOF DATE 
	CONSTRAINT MACHTHRU_ASOF_NN NOT NULL
, UNTIL DATE 
	CONSTRAINT MACHTHRU_UNTIL NOT NULL
, NOTES CHAR(90) 
	CONSTRAINT MACHTHRU_NOTES NOT NULL
, AMOUNT NUMBER 
	CONSTRAINT MACHTHRU_AMT_NN NOT NULL
, CHARGE NUMBER
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.MRA_CLASSES 
(
CLASS VARCHAR2(10)
, PURPOSE VARCHAR2(30)
, CONTACT VARCHAR2(15)
, SHUT_PRI NUMBER(3)
, START_PRI NUMBER(3)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.MRA_MACHINES 
(
ASSETNO VARCHAR2(9)
, CLASS VARCHAR2(10)
, PURPOSE VARCHAR2(30)
, CONTACT VARCHAR2(15)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.MR_CLASSES 
(
CLASS VARCHAR2(10) 
	CONSTRAINT MRCLASSES_CLASS_NN NOT NULL
, SHUT_PRI NUMBER(3)
, START_PRI NUMBER(3)
, PRINC VARCHAR2(8)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 8K NEXT 8K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/



CREATE TABLE HOSTDB.NAME
(
PRINC VARCHAR2(8) 
	CONSTRAINT NAME_PRINC_NN NOT NULL
, NAME VARCHAR2(50) 
	CONSTRAINT NAME_NAME_NN NOT NULL
, LCNAME VARCHAR2(50) 
	CONSTRAINT NAME_LCNAME_NN NOT NULL
, PRI NUMBER(3) 
	CONSTRAINT NAME_PRI_NN NOT NULL
, LNAME VARCHAR2(51) 
	CONSTRAINT NAME_LNAME_NN NOT NULL
, SSN NUMBER(9)
, EMP_NUM NUMBER(7)
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(8)
, LAST_UPDATE DATE
, LAST_UPDATED_BY VARCHAR2(8)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 256K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.NAME_MATCH 
(
NAME VARCHAR2(50) 
	CONSTRAINT NAMEMATCH_NAME_NN NOT NULL
, OWNER VARCHAR2(30)
, TABLE_NAME VARCHAR2(30) 
	CONSTRAINT NAMEMATCH_TBLNAME_NN NOT NULL
, CREATION_DATE DATE
, ID NUMBER(6) 
	CONSTRAINT NAMEMATCH_ID_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.NETREG_HOSTS 
(
HOSTNAME VARCHAR2(255)
, IPADDRESS VARCHAR2(15)
, HWADDR VARCHAR2(20)
, CREATE_DATE DATE
, MODIFY_DATE DATE
, OWNER VARCHAR2(16)
, AFFILIATION VARCHAR2(32)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.NETREG_SUBNETS 
(
VERSION DATE
, ID NUMBER(10) 
	CONSTRAINT NETREGSUBNETS_ID_NN NOT NULL
, NAME VARCHAR2(64) 
	CONSTRAINT NETREGSUBNETS_NAME_NN NOT NULL
, ABBREVIATION VARCHAR2(8) 
	CONSTRAINT NETREGSUBNETS_ABBREV_NN NOT NULL
, BASE_ADDRESS NUMBER(10) 
	CONSTRAINT NETREGSUBNETS_BASEADDR_NN NOT NULL
, NETWORK_MASK NUMBER(10) 
	CONSTRAINT NETREGSUBNETS_NETMASK_NN NOT NULL
, DYNAMIC VARCHAR2(8) 
	CONSTRAINT NETREGSUBNETS_DYNAMIC_NN NOT NULL
, EXPIRE_STATIC NUMBER(10) 
	CONSTRAINT NETREGSUBNETS_EXPIRESTATIC_NN NOT NULL
, EXPIRE_DYNAMIC NUMBER(10) 
	CONSTRAINT NETREGSUBNETS_EXPDYNAMIC_NN NOT NULL
, SHARES NUMBER(10) 
	CONSTRAINT NETREGSUBNETS_SHARE_NN NOT NULL
, FLAGS VARCHAR2(20)
, QUOTA_STATIC NUMBER(10) 
	CONSTRAINT NETREGSUBNETS_QUOTASTATIC_NN NOT NULL
, QUOTA_DYNAMIC NUMBER(10) 
	CONSTRAINT NETREGSUBNETS_QUOTADYNAMIC_NN NOT NULL
, DEFAULT_MODE VARCHAR2(8) 
	CONSTRAINT NETREGSUBNETS_DEFAULTMODE_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 128K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.NETWORKS 
(
NETWORK VARCHAR2(39) 
	CONSTRAINT NETWORKS_NETWORK_NN NOT NULL
, MASK VARCHAR2(39) 
	CONSTRAINT NETWORKS_MASK_NN NOT NULL
, GRP VARCHAR2(10) 
	CONSTRAINT NETWORKS_GRP_NN NOT NULL
, EMIT CHAR(1) DEFAULT '1' 
	CONSTRAINT NETWORKS_EMIT_NN NOT NULL
, CABLE VARCHAR2(10)
, TTL NUMBER(7)
, DESCRIPTION VARCHAR2(30)
, LOCAL VARCHAR2(1) DEFAULT '1' 
	CONSTRAINT NETWORKS_LOCAL_NN NOT NULL
, NETID NUMBER(5)
, NETMASK VARCHAR2(39)
, GATEWAY VARCHAR2(39)
, MIN_ADDR NUMBER(10)
, MAX_ADDR NUMBER(10)
, ADDR_MASK NUMBER(10)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.OS 
(
NAME VARCHAR2(10) 
	CONSTRAINT OS_NAME_NN NOT NULL
, VERS VARCHAR2(10)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 16K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.OSES 
(
NAME VARCHAR2(10) 
	CONSTRAINT OSES_NAME_NN NOT NULL
, CLASS VARCHAR2(10) 
	CONSTRAINT OSES_CLASS_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 16K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.OS_CLASSES 
(
NAME VARCHAR2(10) 
	CONSTRAINT OSCLASSES_NAME_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.PARAM 
(
CHARGE_FIRST DATE NOT NULL
, CHARGE_LAST DATE NOT NULL
, JOURNAL NUMBER(5) NOT NULL
, DESCRIPTION VARCHAR2(30)
, BIWEEKLY_PAY DATE NOT NULL
, ICES_DIST DATE NOT NULL
, LABOR_DIST DATE NOT NULL
, DIST_NAMED DATE NOT NULL
, NAMES_APPLY DATE NOT NULL
, JOURNAL_ENTRY DATE NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 4K NEXT 4K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.PEOPLE_DIST 
(
PRINC VARCHAR2(8) 
	CONSTRAINT PPLDIST_PRINC_NN NOT NULL
,PCT NUMBER(6, 3) 
	CONSTRAINT PPLDIST_PCT_NN NOT NULL
, CHARGE_SRC VARCHAR2(3) 
	CONSTRAINT PPLDIST_CHGSRC_NN NOT NULL
, ACCOUNT NUMBER(6)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 256K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.PLAN_TABLE 
(
STATEMENT_ID VARCHAR2(30)
, TIMESTAMP 
    DATE, "REMARKS" VARCHAR2(80), "OPERATION" VARCHAR2(30), "OPTIONS" 
    VARCHAR2(30), "OBJECT_NODE" VARCHAR2(128), "OBJECT_OWNER" 
    VARCHAR2(30), "OBJECT_NAME" VARCHAR2(30), "OBJECT_INSTANCE" 
    NUMBER, "OBJECT_TYPE" VARCHAR2(30), "OPTIMIZER" 
    VARCHAR2(255), "SEARCH_COLUMNS" NUMBER, "ID" NUMBER, "PARENT_ID" 
    NUMBER, "POSITION" NUMBER, "COST" NUMBER, "CARDINALITY" 
    NUMBER, "BYTES" NUMBER, "OTHER_TAG" VARCHAR2(255), "PARTITION_START" 
    VARCHAR2(255), "PARTITION_STOP" VARCHAR2(255), "PARTITION_ID" 
    NUMBER, "OTHER" LONG)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.PRINCIPAL 
(
PRINC VARCHAR2(8) 
	CONSTRAINT PRINCIPAL_PRINC_NN NOT NULL
, NAME VARCHAR2(8) 
	CONSTRAINT PRINCIPAL_NAME_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.PROJECTS 
(
PROJECT VARCHAR2(30) 
	CONSTRAINT PROJECTS_PROJECT_NN NOT NULL
,CONSTRAINT PROJECTS_PK PRIMARY KEY ("PROJECT")
)  
	ORGANIZATION INDEX 
	PCTFREE 10 INITRANS 1 MAXTRANS 255 
	STORAGE(INITIAL 32K NEXT 32K FREELISTS 1 FREELIST GROUPS 1) 
	TABLESPACE "APPS" 
	LOGGING 
	NOCOMPRESS 
/

CREATE TABLE HOSTDB.PROJECT_CENTER 
(
PROJECT VARCHAR2(30) 
	CONSTRAINT PRJCENTER_PROJECT_NN NOT NULL
, SPONSOR VARCHAR2(8)
, CENTER VARCHAR2(7) 
	CONSTRAINT PRJCENTER_CENTER_NN NOT NULL
, PRI NUMBER(3) 
	CONSTRAINT PRJCENTER_PRI_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.PROJECT_COMBOS 
(
NAME VARCHAR2(30) 
	CONSTRAINT PRJCOMBO_NAME_NN NOT NULL
, SUBNAME VARCHAR2(12) 
	CONSTRAINT PRJCOMBO_SUBNAME_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.PROTOCOLS 
(
NAME VARCHAR2(3) 
	CONSTRAINT PRTCLS_NAME_NN NOT NULL
, DESCRIPTION VARCHAR2(20) 
	CONSTRAINT PRTCLS_DESC_NN NOT NULL
, COSTED CHAR(1) 
	CONSTRAINT PRTCLS_COSTED_NN NOT NULL
, ALIASED CHAR(1)
, HOSTNAME_CONTEXT VARCHAR2(10)
, IPADDRESS_CONTEXT VARCHAR2(10)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.PTA_STATUS 
(
EXTRACT_DATE DATE
, PTA VARCHAR2(68)
, PROJECT_ID NUMBER
, PROJ_NAME VARCHAR2(30)
, PROJECT_NUMBER VARCHAR2(30)
, PROJ_START_DATE DATE
, PROJ_COMPLETION_DATE DATE
, PROJ_CLOSED_DATE DATE
, PROJ_STATUS_CODE VARCHAR2(30)
, TASK_NUMBER VARCHAR2(25)
, TASK_COMPLETION_DATE DATE
, TASK_CHARGE_FLAG VARCHAR2(1)
, AWARD_NUMBER VARCHAR2(15)
, AWARD_NAME VARCHAR2(30)
, AWARD_START_DATE_ACTIVE DATE
, AWARD_END_DATE_ACTIVE DATE
, AWARD_CLOSED_DATE DATE
, AWARD_STATUS VARCHAR2(30)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 256K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.QUALIFIERS 
(
CODE CHAR(1) 
	CONSTRAINT QUALIFIERS_CODE_NN NOT NULL
, KEYWORD CHAR(13) 
	CONSTRAINT QUALIFIERS_KEYWORD_NN NOT NULL
, DESCRIPTION CHAR(60) 
	CONSTRAINT QUALIFIERS_DESC_NN NOT NULL
, NO_CHARGE CHAR(1)
, NO_ATTR CHAR(1)
, NO_NET CHAR(1)
, NO_SOFTWARE VARCHAR2(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.REMCOLAUTH 
(
KGROUP VARCHAR2(8) 
	CONSTRAINT REMCOLAUTH_KGRP_NN NOT NULL
, TAB VARCHAR2(20) 
	CONSTRAINT REMCOLAUTH_TAB_NN NOT NULL
, COL VARCHAR2(20) 
	CONSTRAINT REMCOLAUTH_COL_NN NOT NULL
, AUTH CHAR(4) 
	CONSTRAINT REMCOLAUTH_AUTH_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.REPORT_CHARGE 
(
TYPE VARCHAR2(1)
, LIMBO_FLAG CHAR(1)
, JID NUMBER(5)
, TRANS_DATE DATE
, POST_DATE DATE
, CHARGE NUMBER
, PCT NUMBER(5, 2)
, AMOUNT NUMBER
, OS VARCHAR2(10)
, NAME VARCHAR2(50)
, MACH_USER VARCHAR2(50)
, MACH_LOC VARCHAR2(30)
, FUND VARCHAR2(6)
, FUNC VARCHAR2(3)
, ACT VARCHAR2(3)
, ORG VARCHAR2(6)
, ENT VARCHAR2(2)
, PROJ VARCHAR2(8)
, TASK VARCHAR2(8)
, AWARD VARCHAR2(8)
, NOTES VARCHAR2(50)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.RUN_ADJUST_EXCEPTION_RECORDS 
(
ID NUMBER
, TYPE VARCHAR2(4)
, TRANS_DATE DATE
, ACCOUNT NUMBER
, PTA_LIMBO_ACCT_STRING VARCHAR2(25)
, GL_LIMBO_ACCT_STRING VARCHAR2(25)
, NOTES VARCHAR2(50)
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(50)
, LAST_UPDATE_DATE DATE
, LAST_UPDATED_BY VARCHAR2(50)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 10 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.RUN_ADJUST_FAILED_ACCTS 
(
AMOUNT NUMBER
, NUM_RECS NUMBER
, TYPE VARCHAR2(5)
, ACCT VARCHAR2(25)
, PROJ_START_DATE DATE
, PROJ_COMPLETION_DATE DATE
, PROJ_CLOSED_DATE DATE
, PROJ_STATUS_CODE VARCHAR2(30)
, TASK_COMPLETION_DATE DATE
, TASK_CHARGE_FLAG VARCHAR2(1)
, AWARD_START_DATE_ACTIVE DATE
, AWARD_END_DATE_ACTIVE DATE
, AWARD_CLOSED_DATE DATE
, AWARD_STATUS VARCHAR2(30)
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(50)
, LAST_UPDATE_DATE DATE
, LAST_UPDATED_BY VARCHAR2(50)
, TRANS_DATE DATE
, ACCT_ID NUMBER
, NOTES VARCHAR2(50)
, TRANS_ID NUMBER
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/
COMMENT ON COLUMN "HOSTDB"."RUN_ADJUST_FAILED_ACCTS"."TRANS_ID" 
    IS 'HR_ID OR WR_ID';

CREATE TABLE HOSTDB.RUN_ADJUST_LOG 
(
RUN_DATE DATE
, JOURNAL NUMBER
, PROCESSED NUMBER
, LIMBO NUMBER
, ERROR_MESSAGE VARCHAR2(1000)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.SERVICES 
(
ID NUMBER(3) 
	CONSTRAINT SERVICES_ID_NN NOT NULL
, CATEGORY VARCHAR2(40)
, ATTR VARCHAR2(10)
, DESCRIPTION VARCHAR2(1)
, MONTHLY VARCHAR2(1)
, TYPE VARCHAR2(1) 
	CONSTRAINT SERVICES_TYPE_NN NOT NULL
, SUBTYPE VARCHAR2(3) 
	CONSTRAINT SERVICES_SUBTYPE_NN NOT NULL
, OS VARCHAR2(10)
, GENERIC VARCHAR2(11)
, OTHER VARCHAR2(10)
, OS_CLASS VARCHAR2(10)
, ATTR2 VARCHAR2(10)
, SPECIFIC VARCHAR2(11)
, WEBCODE VARCHAR2(3)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 128K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 20 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.SPECIFICS 
(
NAME VARCHAR2(11) 
	CONSTRAINT SPECIFICS_NAME_NN NOT NULL
,CONSTRAINT BLDGS_PK PRIMARY KEY ("CODE")
) 
	ORGANIZATION INDEX 
	PCTFREE 10 INITRANS 1 MAXTRANS 255 
	STORAGE(INITIAL 32K NEXT 32K FREELISTS 1 FREELIST GROUPS 1) 
	TABLESPACE "APPS" 
	LOGGING 
	NOCOMPRESS 
/

CREATE TABLE HOSTDB.TMCD_LDR 
(
BATCH DATE 
	CONSTRAINT TMCDLDR_BATCH_NN NOT NULL
, TRCODE VARCHAR2(2) 
	CONSTRAINT TMCDLDR_TRCODE_NN NOT NULL
, SSN NUMBER(9)
, LNAME VARCHAR2(21) 
	CONSTRAINT TMCDLDR_LNAME_NN NOT NULL
, FNAME VARCHAR2(16)
, HOURS NUMBER(6, 2) 
	CONSTRAINT TMCDLDR_HOURS_NN NOT NULL
, HOURS_OT NUMBER(6, 2) 
	CONSTRAINT TMCDLDR_HOURSOT_NN NOT NULL
, HED VARCHAR2(2) 
	CONSTRAINT TMCDLDR_HED_NN NOT NULL
, PAYDATE DATE 
	CONSTRAINT TMCDLDR_PAYDATE_NN NOT NULL
, HOME_ORG VARCHAR2(6) 
	CONSTRAINT TMCDLDR_HOMEORG_NN NOT NULL
, KIND VARCHAR2(4) 
	CONSTRAINT TMCDLDR_KIND_NN NOT NULL
, PROJECT VARCHAR2(8)
, TASK VARCHAR2(8)
, AWARD VARCHAR2(8)
, EXP_ORG VARCHAR2(6)
, FUNDING VARCHAR2(6)
, FUNCTION VARCHAR2(3)
, ACTIVITY VARCHAR2(3)
, ORG VARCHAR2(6)
, ENTITY VARCHAR2(2)
, EMP_NUM NUMBER(7) 
	CONSTRAINT TMCDLDR_EMPNUM_NN NOT NULL
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.TMCD_NOMATCH 
(
LNAME VARCHAR2(21) 
	CONSTRAINT TMCDNOMATCH_LNAME_NN NOT NULL
, FNAME VARCHAR2(16)
, APPOINTMENT NUMBER(7) 
	CONSTRAINT TMCDNOMATCH_EMPNO_NN NOT NULL
, BATCH DATE 
	CONSTRAINT TMCDNOMATCH_BATCH_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.TMCD_RECORDED 
(
PERIOD_LAST DATE 
	CONSTRAINT TMCDRCD_PERIODLAST_NN NOT NULL
, PRINC VARCHAR2(8)
, PCT NUMBER(5, 2)
, CHARGE_SRC VARCHAR2(3) 
	CONSTRAINT TMCDRCD_CHGSRC_NN NOT NULL
, TRCODE VARCHAR2(2) 
	CONSTRAINT TMCDRCD_TRCODE_NN NOT NULL
, SSN NUMBER(9)
, LNAME VARCHAR2(21) 
	CONSTRAINT TMCDRCD_LNAME_NN NOT NULL
, FNAME VARCHAR2(16)
, HOURS NUMBER(6, 2) 
	CONSTRAINT TMCDRCD_HOURS_NN NOT NULL
, HOURS_OT NUMBER(6, 2) 
	CONSTRAINT TMCDRCD_HOURSOT_NN NOT NULL
, HED VARCHAR2(2) 
	CONSTRAINT TMCDRCD_HED_NN NOT NULL
, PAYDATE DATE 
	CONSTRAINT TMCDRCD_PAYDAY_NN NOT NULL
, HOME_ORG VARCHAR2(6) 
	CONSTRAINT TMCDRCD_HOMEORG_NN NOT NULL
, KIND VARCHAR2(4) 
	CONSTRAINT TMCDRCD_KIND_NN NOT NULL
, BATCH DATE 
	CONSTRAINT TMCDRCD_BATCH_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT TMCDRCD_ACCT_NN NOT NULL
, EXP_ORG VARCHAR2(6)
, APPOINTMENT NUMBER(7)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 256K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 20 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.TRIGDEF_Q 
(
ROW_ID ROWID
, TAB VARCHAR2(20) 
	CONSTRAINT TRIGDEFQ_TAB_NN NOT NULL
, SEQ NUMBER(9) 
	CONSTRAINT TRIGDEFQ_SEQ_NN NOT NULL
, TEXT1 VARCHAR2(30)
, TEXT2 VARCHAR2(12)
, NUM1 NUMBER(7)
, NUM2 NUMBER(7))  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 32K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.WHO 
(
PRINC VARCHAR2(8) 
	CONSTRAINT WHO_PRINC_NN NOT NULL
, ID NUMBER 
	CONSTRAINT WHO_ID_NN NOT NULL
, SPONSOR VARCHAR2(8)
, TYPE NUMBER 
	CONSTRAINT WHO_TYPE_NN NOT NULL
, DEPT CHAR(5)
, EMP_IND CHAR(1)
, TITLE CHAR(30)
, PROJECT VARCHAR2(30)
, CHARGE_BY CHAR(1)
, DIST NUMBER(6)
, PCT NUMBER(6, 3)
, OPROJECT CHAR(1)
, SUBPROJECT VARCHAR2(12)
, DIST_SRC VARCHAR2(3)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 512K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_ADJUST_CHARGE 
(
WR_ID NUMBER(6) 
	CONSTRAINT WAC_WRID_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT WAC_PCT_NN NOT NULL
, CHARGE NUMBER(6, 2) 
	CONSTRAINT WAC_CHG_NN NOT NULL
, AMOUNT NUMBER(6, 2) 
	CONSTRAINT WAC_AMT_NN NOT NULL
, TRANS_DATE DATE 
	CONSTRAINT WAC_TRANSDATE_NN NOT NULL
, SERVICE_ID NUMBER(3) 
	CONSTRAINT WAC_SVCID_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT WAC_ACCT_NN NOT NULL
, JOURNAL NUMBER(5)
, NOTES VARCHAR2(50)
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(50)
, LAST_UPDATE_DATE DATE
, LAST_UPDATED_BY VARCHAR2(50)
, HOLD_FLAG VARCHAR2(1)
, LIMBO_FLAG VARCHAR2(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 128K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_ATTR 
(
PRINC VARCHAR2(8) 
	CONSTRAINT WHOATTR_PRINC_NN NOT NULL
, ATTR VARCHAR2(3) 
	CONSTRAINT WHOATTR_ATTR_NN NOT NULL
, SENSE CHAR(1) 
	CONSTRAINT WHOATTR_SENSE_NN NOT NULL
, NOTES VARCHAR2(30)
, PURGE CHAR(1)
, IS_IMPORT VARCHAR2(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_ATTR_UP 
(
PRINC VARCHAR2(8) 
	CONSTRAINT WHOATTRUP_PRINC_NN NOT NULL
, ATTR VARCHAR2(3) 
	CONSTRAINT WHOATTRUP_ATTR_NN NOT NULL
, SENSE CHAR(1) 
	CONSTRAINT WHOATTRUP_SENSE_NN NOT NULL
, NOTES VARCHAR2(30)
, PURGE CHAR(1)
, IS_IMPORT VARCHAR2(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_CHARGE 
(
PRINC VARCHAR2(8) 
	CONSTRAINT WHOCHARGE_PRINC_NN NOT NULL
, PROJECT VARCHAR2(20)
, SUPERVISOR VARCHAR2(8)
, CENTER VARCHAR2(7) 
	CONSTRAINT WHOCHARGE_CENTER_NN NOT NULL
, PCT NUMBER(5) 
	CONSTRAINT WHOCHARGE_PCT_NN NOT NULL
, KIND CHAR(1)
, CHARGE_BGN DATE
, CHARGE_END DATE
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/



CREATE TABLE HOSTDB.WHO_CHARGED 
(
WR_ID NUMBER(6) 
	CONSTRAINT WC_WRID_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT WC_PCT_NN NOT NULL
, CHARGE NUMBER(6, 2) 
	CONSTRAINT WC_CHG_NN NOT NULL
, AMOUNT NUMBER(6, 2) 
	CONSTRAINT WC_AMOUNT_NN NOT NULL
, TRANS_DATE DATE 
	CONSTRAINT WC_TRANSDATE_NN NOT NULL
, SERVICE_ID NUMBER(3) 
	CONSTRAINT WC_SVCID_NN NOT NULL
, JOURNAL NUMBER(5) 
	CONSTRAINT WC_JNL_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT WC_ACCT_NN NOT NULL
, ACCOUNT_FLAG CHAR(1)
, NOTES VARCHAR2(50)
, CREATION_DATE DATE
, CREATED_BY VARCHAR2(50)
, LAST_UPDATE_DATE DATE
, LAST_UPDATED_BY VARCHAR2(50)
)  
    TABLESPACE "COSTING_LG" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 4M NEXT 128K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_CHARGE_NRM 
(
PRINC VARCHAR2(8) 
	CONSTRAINT WHOCHGNRM_PRINC_NN NOT NULL
, PROJECT VARCHAR2(20)
, SUPERVISOR VARCHAR2(8)
, CENTER VARCHAR2(7) 
	CONSTRAINT WHOCHGNRM_CENTER_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT WHOCHGNRM_PCT_NN NOT NULL
, KIND CHAR(1)
, CHARGE_BGN DATE
, CHARGE_END DATE
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_RECORDED 
(
ID NUMBER(6) 
	CONSTRAINT WHOR_ID_NN NOT NULL
,PRINC VARCHAR2(8) 
	CONSTRAINT WHOR_PRINC_NN NOT NULL
, NAME VARCHAR2(50) 
	CONSTRAINT WHOR_NAME_NN NOT NULL
, CHARGE_SRC VARCHAR2(3)
, PROJECT VARCHAR2(30)
, SUBPROJECT VARCHAR2(12)
, SPONSOR VARCHAR2(8)
)  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 2M NEXT 128K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_SERVICE 
(
PRINC VARCHAR2(8) 
	CONSTRAINT WHOSVC_PRINC_NN NOT NULL
, SERVICE_ID NUMBER(3) 
	CONSTRAINT WHOSVC_SVCID_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT WHOSVC_PCT_NN NOT NULL
, JOURNAL NUMBER(5)
, TRANS_DATE DATE
, WR_ID NUMBER(6)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 128K NEXT 128K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/


CREATE TABLE HOSTDB.WHO_SERVICE_CHARGE 
(
PRINC VARCHAR2(8) 
	CONSTRAINT WSC_PRINC_NN NOT NULL
, PCT NUMBER(5, 2) 
	CONSTRAINT WSC_PCT_NN NOT NULL
, CHARGE NUMBER(6, 2) 
	CONSTRAINT WSC_CHG_NN NOT NULL
, AMOUNT NUMBER(6, 2) 
	CONSTRAINT WSC_AMT_NN NOT NULL
, ACCOUNT NUMBER(6) 
	CONSTRAINT WSC_ACCT_NN NOT NULL
, SERVICE_ID NUMBER(3) 
	CONSTRAINT WSC_SVCID_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 256K NEXT 128K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_SERVICE_MATRIX 
(
PRINC VARCHAR2(8) 
	CONSTRAINT WHOSVCMATRIX_PRINC_NN NOT NULL
, GENERAL CHAR(1)
, AFS CHAR(1)
, PRINT CHAR(1)
, DEVELOP_ST CHAR(1)
, DEVELOP_LT CHAR(1)
, PURCHASE CHAR(1)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 128K NEXT 64K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_THRU 
(
PRINC CHAR(8) 
	CONSTRAINT WHOTHRU_PRINC_NN NOT NULL
, ATTR CHAR(30) 
	CONSTRAINT WHOTHRU_ATTR_NN NOT NULL
, ASOF DATE 
	CONSTRAINT WHOTHRU_ASOF_NN NOT NULL
, UNTIL DATE 
	CONSTRAINT WHOTHRU_UNTIL_NN NOT NULL
, NOTES CHAR(90) 
	CONSTRAINT WHOTHRU_NOTES_NN NOT NULL
, AMOUNT NUMBER NOT NULL
, CHARGE NUMBER
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 16K MINEXTENTS 2 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_TYPES 
(
ID NUMBER(2) 
	CONSTRAINT WHOTYPES_ID_NN NOT NULL
, CODE CHAR(1) 
	CONSTRAINT WHOTYPES_CODE_NN NOT NULL
, DESCRIP VARCHAR2(20) 
	CONSTRAINT WHOTYPES_DESC_NN NOT NULL
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 16K NEXT 8K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ZONES 
(
NAME VARCHAR2(40) 
	CONSTRAINT ZONES_NAME_NN NOT NULL
, GRP VARCHAR2(10) 
	CONSTRAINT ZONES_GRP_NN NOT NULL
, EMIT CHAR(1) DEFAULT '1' 
	CONSTRAINT ZONES_EMIT_NN NOT NULL
, TTL NUMBER(7)
, DESCRIPTION VARCHAR2(30)
, LOCAL VARCHAR2(1) DEFAULT '1' 
	CONSTRAINT ZONES_LOCAL_NN NOT NULL
, METHOD CHAR(1)
, CONTACT VARCHAR2(30)
, SOURCE VARCHAR2(80)
)  
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 32K NEXT 16K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.ZONE_METHODS 
(
CODE CHAR(1)
, DESCRIPTION VARCHAR2(10)
, SOURCE VARCHAR2(30)
)  
    TABLESPACE "APPS" PCTFREE 5 PCTUSED 60 INITRANS 2 MAXTRANS 
    255 
    STORAGE ( INITIAL 8K NEXT 8K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 
/

CREATE TABLE HOSTDB.WHO_REPORT 
(
USRPRINC VARCHAR2(8)
, NAME VARCHAR2(50)
, PCT_ACCT NUMBER
, SPNSPRINC VARCHAR2(8)
, ACCT_STATUS VARCHAR2(8)
, JEEVES_PRI VARCHAR2(1)
, JEEVES_CASE VARCHAR2(10)
, JEEVES_SRC VARCHAR2(30)
, DIST_SRC VARCHAR2(30)
, DIST_PCT NUMBER
, ACCT_ID NUMBER
, ACCT VARCHAR2(40)
, GENERAL VARCHAR2(1)
, AFS VARCHAR2(1)
, PRINT VARCHAR2(1)
, DEV_ST VARCHAR2(1)
, DEV_LT VARCHAR2(1)
, PURCH VARCHAR2(1))  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 2M NEXT 128K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING
/

COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."USRPRINC" IS 
    'who.princ';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."NAME" IS 'name.name';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."PCT_ACCT" IS 'who.pct';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."SPNSPRINC" IS 
    'WHO.SPONSOR';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."ACCT_STATUS" IS 
    'accounts.flag';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."JEEVES_PRI" IS 
    'derived';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."JEEVES_CASE" IS 
    'derived';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."JEEVES_SRC" IS 
    'derived';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."DIST_SRC" IS 
    'who.dist_src';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."DIST_PCT" IS 'percent 
    of charge to this account';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."ACCT_ID" IS 
    'accounts.id';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."GENERAL" IS 
    'who_service_matrix';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."AFS" IS 
    'who_service_matrix';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."PRINT" IS 
    'who_service_matrix';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."DEV_ST" IS 
    'who_service_matrix';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."DEV_LT" IS 
    'who_service_matrix';
COMMENT ON COLUMN "HOSTDB"."WHO_REPORT"."PURCH" IS 
    'who_service_matrix'

CREATE TABLE HOSTDB.HOST_REPORT 
(
ASSETNO VARCHAR2(9) NOT NULL
, HOSTNAME VARCHAR2(40)
, SERIALNUM VARCHAR2(20)
, HWADDR VARCHAR2(20)
, IPADDR VARCHAR2(30)
, CPUMODEL VARCHAR2(20)
, OS VARCHAR2(32)
, PLATFORM VARCHAR2(11)
, QUALIFIER VARCHAR2(40)
, PRI NUMBER
, CHARGE_BY VARCHAR2(1)
, DIST NUMBER
, DIST_SRC VARCHAR2(3)
, USRPRINC VARCHAR2(8)
, PRJPRINC VARCHAR2(8)
, PRINC VARCHAR2(8)
, PROJECT VARCHAR2(30)
, SUBPROJECT VARCHAR2(12)
, DIST_PCT NUMBER
, ACCT_ID NUMBER
, ACCT VARCHAR2(30)
, ACCT_STATUS VARCHAR2(8)
, LOCATION VARCHAR2(30)
, NETWORK VARCHAR2(1)
, MACH_ROOM VARCHAR2(10)
, HARD_LABOR VARCHAR2(1)
, HARD_REPAIR VARCHAR2(1)
, SOFT_SUPPORT VARCHAR2(1)
, SOFT_LICENSING VARCHAR2(1)
, BACKUP VARCHAR2(1))  
    TABLESPACE "COSTING" PCTFREE 10 PCTUSED 40 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 2M NEXT 256K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING
/
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."ASSETNO" IS 
    'machtab.assetno';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."HOSTNAME" IS 
    'hostab.hostname';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."SERIALNUM" IS 
    'capequip.serialnum';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."HWADDR" IS 
    'machtab.hwaddr';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."IPADDR" IS 
    'hostab.ipaddress';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."CPUMODEL" IS 
    'machtab.cpumodelext';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."OS" IS 'hostab.os';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."PLATFORM" IS 
    'mach_equiv.generic';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."QUALIFIER" IS 
    'qualifier.keyword';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."CHARGE_BY" IS 
    'machtab.usage';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."DIST" IS 
    'machtab.dist';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."DIST_SRC" IS 
    'MACHTAB.DIST_SRC';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."USRPRINC" IS 'primary 
    user';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."PRJPRINC" IS 'PROJECT 
    CONTACT  machtab.prjprinc';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."PRINC" IS 'EQUIPMENT 
    CONTACT capequip.princ';
COMMENT ON COLUMN "HOSTDB"."HOST_REPORT"."ACCT" IS 'accounts,
    distname,machtab.dist';



CREATE TABLE HOSTDB.GL_REPORT 
(
TYPE VARCHAR2(1)
, LIMBO_FLAG CHAR(1)
, JID NUMBER(5)
, ASSETNO VARCHAR(9)
, PRINC VARCHAR(8)
, TRANS_DATE DATE
, POST_DATE DATE
, CHARGE NUMBER
, PCT NUMBER(5, 2)
, AMOUNT NUMBER
, OS VARCHAR2(10)
, NAME VARCHAR2(50)
, MACH_USER VARCHAR2(50)
, MACH_LOC VARCHAR2(30)
, FUND VARCHAR2(6)
, FUNC VARCHAR2(3)
, ACT VARCHAR2(3)
, ORG VARCHAR2(6)
, ENT VARCHAR2(2)
, PROJ VARCHAR2(8)
, TASK VARCHAR2(8)
, AWARD VARCHAR2(8)
, NOTES VARCHAR2(50)
, SERVICES VARCHAR2(30)) 
    TABLESPACE "APPS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 4M NEXT 256K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING
/ 

CREATE OR REPLACE VIEW HOSTDB.DIST_ACCOUNTS (
"PCT"
,"DIST"
,"ID"
,"FLAG"
,"PROJECT"
,"TASK"
,"AWARD"
,"FUNDING"
,"FUNCTION"
,"ACTIVITY"
,"ORG"
,"ENTITY"
,"EXPIRES"
,"CREATION_DATE"
,"CREATED_BY"
,"LAST_UPDATE_DATE"
,"LAST_UPDATED_BY"
)
    AS 
SELECT dist.pct,dist.dist,accounts.* 
 FROM dist,accounts 
WHERE dist.account=accounts.id
/

exit;
