
  CREATE TABLE ESC.ESC_TPLC
   (	ESC_PLAN_ID INTEGER NOT NULL ENABLE,
	COMN_MODL_ID INTEGER NOT NULL ENABLE,
	PLAN_COMN_BEG_TS TIMESTAMP (6) NOT NULL ENABLE,
	PLAN_COMN_END_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	SKU_ID NUMBER(7,0),
	 CONSTRAINT ESCTPLC_PK PRIMARY KEY (ESC_PLAN_ID, COMN_MODL_ID)
	 ,CONSTRAINT ESCRPLC1 FOREIGN KEY (COMN_MODL_ID)
	  REFERENCES ESC.ESC_TCMD (COMN_MODL_ID) ENABLE NOVALIDATE,
	 CONSTRAINT ESCRPLC2 FOREIGN KEY (ESC_PLAN_ID)
	  REFERENCES ESC.ESC_TPLN (ESC_PLAN_ID) ENABLE NOVALIDATE
   ) 
;


Create INDEX  ESC.IX_ESCTPLC_1  on ESC.ESC_TPLC   (COMN_MODL_ID);

