
  CREATE TABLE ESC.ESC_TCSI
   (	ESC_CUST_ACCT_ID INTEGER NOT NULL ENABLE,
	INST_1ST_NM VARCHAR2(25),
	INST_MDL_INTL VARCHAR2(1),
	INST_LAST_NM VARCHAR2(25),
	INST_NM_PREFIX_TYP VARCHAR2(7),
	INST_NM_SUFFIX_TYP VARCHAR2(3),
	INST_ADDR_ST_NBR VARCHAR2(10),
	INST_ADDR_ST_NM VARCHAR2(30),
	INST_ADDR_UNIT_ID VARCHAR2(10),
	INST_ADDR_CITY_NM VARCHAR2(30),
	INST_STATE_ABBR VARCHAR2(5),
	INST_ADDR_ZIP VARCHAR2(7),
	INST_ADDR_ZIP4 VARCHAR2(4),
	INST_CNTRY_ID VARCHAR2(2),
	INST_HOME_PH_AREA VARCHAR2(3),
	INST_HOME_PH_NBR VARCHAR2(7),
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	PCI_CRCARD_TYPE VARCHAR2(1),
	EMAIL_ADDR_ID VARCHAR2(55),
	WORK_PH_AREA_NBR VARCHAR2(3),
	WORK_PH_NBR VARCHAR2(7),
	WORK_PH_EXT VARCHAR2(5),
	COMN_DEPT_TYP VARCHAR2(4) DEFAULT 'DFLT' NOT NULL ENABLE,
	CRCD_AUTH_ID VARCHAR2(16),
	CUST_RAC_USR_ID VARCHAR2(30),
	CUST_RAC_PSWD_TXT VARCHAR2(8),
	LANG_LCLE_ID NUMBER(10,0),
	CRCARD_ACCT_ID RAW(32),
	CRCARD_EXP_YEAR RAW(32),
	CRCARD_EXP_MNTH RAW(32),
	CRCARD_1ST_NM RAW(32),
	CRCARD_LAST_NM RAW(32),
	CRCARD_MDL_INTL RAW(16),
	CRCARD_TYPE RAW(16),
	CVRD_SKU_ID NUMBER(7,0),
	 CONSTRAINT ESCTCSI_PK PRIMARY KEY (ESC_CUST_ACCT_ID)
	 ,CONSTRAINT ESCRCSI1 FOREIGN KEY (LANG_LCLE_ID)
	  REFERENCES ESC.LANG_LCLE (LANG_LCLE_ID) ENABLE
   ) 
;


