
	 --,CONSTRAINT CHK_SLS_ADT_PCSD_STAT_TYP CHECK (SLS_ADT_PCSD_STAT_TYP in ('PCSD', 'LDED', 'PSNG', 'FAIL')) ENABLE NOVALIDATE
  CREATE TABLE ESC.ESC_TEGT
   (	TRANS_AUDIT_ID INTEGER NOT NULL ENABLE,
	SLS_TRANS_NBR NUMBER(5,0) NOT NULL ENABLE,
	REGSTR_NBR NUMBER(3,0) NOT NULL ENABLE,
	SLS_TRANS_TS TIMESTAMP (6) NOT NULL ENABLE,
	LOC_ID NUMBER(5,0) NOT NULL ENABLE,
	AUDIT_TYP VARCHAR2(4) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	COMN_AR_TYP VARCHAR2(4),
	POST_SKU_ID NUMBER(7,0),
	SALE_AMT NUMBER(9,2),
	GL_CD VARCHAR2(6),
	SALE_POST_TS TIMESTAMP (6),
	SLS_ADT_PCSD_STAT_TYP VARCHAR2(4) DEFAULT 'LDED' NOT NULL ENABLE,
	SLS_ADT_PRCS_MC_NM VARCHAR2(10),
	CC_FEED_PCSD_STAT_TYP VARCHAR2(4) NOT NULL ENABLE,
	 CONSTRAINT ESCTEGT_PK PRIMARY KEY (TRANS_AUDIT_ID)
   ) 
;

