CREATE TABLE ESC.ESC_CUSTCST
(	
    CUST_ID NUMBER(18,0) NOT NULL ENABLE,
	CUST_1ST_NM VARCHAR2(25) NOT NULL ENABLE,
	CUST_MDL_INTL VARCHAR2(1),
	CUST_LAST_NM VARCHAR2(25) NOT NULL ENABLE,
	CUST_NM_PREFIX_TYP VARCHAR2(7),
	CUST_ADDR_ST_NBR VARCHAR2(10),
	CUST_ADDR_ST_NM VARCHAR2(30) NOT NULL ENABLE,
	CUST_ADDR_UNIT_ID VARCHAR2(10),
	CUST_ADDR_CITY_NM VARCHAR2(30) NOT NULL ENABLE,
	STATE_ABBR VARCHAR2(5) NOT NULL ENABLE,
	CUST_ADDR_ZIP VARCHAR2(7) NOT NULL ENABLE,
	CUST_ADDR_ZIP4 VARCHAR2(4),
	CNTRY_ID VARCHAR2(2) NOT NULL ENABLE,
	EMAIL_ADDR_ID VARCHAR2(55),
	HOME_PH_AREA_NBR VARCHAR2(3),
	HOME_PH_NBR VARCHAR2(7) NOT NULL ENABLE,
	WORK_PH_AREA_NBR VARCHAR2(3),
	WORK_PH_NBR VARCHAR2(7),
	WORK_PH_EXT VARCHAR2(5),
	EC_SENT_FLG CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	CUST_NM_SUFFIX_TYP VARCHAR2(3),
	 CONSTRAINT CUSTCST_PK PRIMARY KEY (CUST_ID)
) 
;

Create INDEX  ESC.IX_ESCCUSTCST_1  on ESC.ESC_CUSTCST   ( CUST_LAST_NM ,CUST_1ST_NM ,CUST_ID);
Create INDEX  ESC.IX_ESCCUSTCST_2  on ESC.ESC_CUSTCST   ( HOME_PH_NBR ,CUST_LAST_NM ,CUST_1ST_NM ,HOME_PH_AREA_NBR);
Create INDEX  ESC.IX_ESCCUSTCST_3  on ESC.ESC_CUSTCST   (EC_SENT_FLG);

