
  CREATE TABLE ESC.ESC_TCPT
   (	CHGBK_PRD_TYP VARCHAR2(4) NOT NULL ENABLE,
	CHGBK_PRD_TYP_NM VARCHAR2(30) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	CHGBK_PRD_TYP_DESC VARCHAR2(256) NOT NULL ENABLE,
	 CONSTRAINT ESCTCPT_PK PRIMARY KEY (CHGBK_PRD_TYP)
   )
;


