
  CREATE TABLE ESC.ESC_TSLT
   (	SLS_TRANS_NBR NUMBER(5,0) NOT NULL ENABLE,
	REGSTR_NBR NUMBER(3,0) NOT NULL ENABLE,
	SLS_TRANS_TS TIMESTAMP (6) NOT NULL ENABLE,
	LOC_ID NUMBER(5,0) NOT NULL ENABLE,
	ESC_TRANS_SRC_TYP VARCHAR2(4) NOT NULL ENABLE,
	ESC_TRANS_VOID_FLG VARCHAR2(1) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	 CONSTRAINT ESCTSLT_PK PRIMARY KEY (LOC_ID, SLS_TRANS_NBR, REGSTR_NBR, SLS_TRANS_TS)
   )
;


