CREATE TABLE ESC.ESC_SKUTSKU
   (    SKU_ID NUMBER(7,0) NOT NULL ENABLE,
        SKU_DESC VARCHAR2(30) NOT NULL ENABLE,
        SKU_MFG_MODEL_ID VARCHAR2(10) NOT NULL ENABLE,
        SUBCLASS_ID NUMBER(4,0) NOT NULL ENABLE,
        CLASS_ID NUMBER(4,0) NOT NULL ENABLE,
        DEPT_ID NUMBER(3,0) NOT NULL ENABLE,
        SKU_ACTV_FLG VARCHAR2(1) NOT NULL ENABLE,
        PRIM_VNDR_ID NUMBER(9,0) NOT NULL ENABLE,
        REC_CREATE_DT DATE NOT NULL ENABLE,
        REC_UPD_PGM_TS TIMESTAMP (6) NOT NULL ENABLE,
        REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
        REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
         CONSTRAINT SKUTSKU_PK PRIMARY KEY (SKU_ID)
   ) 
;
