
  CREATE TABLE ESC.ESC_TDPT
   (	COMN_DEPT_TYP VARCHAR2(4) NOT NULL ENABLE,
	COMN_DEPT_NM VARCHAR2(30) NOT NULL ENABLE,
	COMN_DEPT_DESC VARCHAR2(255) NOT NULL ENABLE,
	COMN_DEPT_ACTV_FLG VARCHAR2(1) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	 CONSTRAINT ESCTDPT_PK PRIMARY KEY (COMN_DEPT_TYP)
   ) 
;
