
  CREATE TABLE ESC.ESC_TPAK
   (	SKU_ID NUMBER(7,0) NOT NULL ENABLE,
	ESC_PLAN_ID INTEGER NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	 CONSTRAINT ESCTPAK_PK PRIMARY KEY (SKU_ID, ESC_PLAN_ID)
   )
;


--Create INDEX  ESC.IX_ESCTPAK_1  on ESC.ESC_TPAK   (ESC_PLAN_ID ,SKU_ID);
