
  CREATE TABLE ESC.ESC_TCMH
   (	ESC_CUST_ACCT_ID INTEGER NOT NULL ENABLE,
	ESC_COMM_HIST_NBR INTEGER NOT NULL ENABLE,
	FILE_ACTVTY_TYP VARCHAR2(4) NOT NULL ENABLE,
	ESC_COMM_TS TIMESTAMP (6),
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	VNDR_ID NUMBER(9,0),
	VNDR_SUBTYP VARCHAR2(3),
	ESC_LN_SEQ INTEGER,
	 CONSTRAINT ESCTCMH_PK PRIMARY KEY (ESC_CUST_ACCT_ID, ESC_COMM_HIST_NBR, FILE_ACTVTY_TYP)
   )
;


Create INDEX  ESC.IX_ESCTCMH_1  on ESC.ESC_TCMH   (ESC_COMM_TS);

