
  CREATE TABLE ESC.ESC_TLIA
   (	ESC_LN_SEQ INTEGER NOT NULL ENABLE,
	ATRIB_NM VARCHAR2(10) NOT NULL ENABLE,
	ESC_ATRIB_VAL VARCHAR2(100) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	 CONSTRAINT ESCTLIA_PK PRIMARY KEY (ESC_LN_SEQ, ATRIB_NM)
   )
;


Create INDEX  ESC.IX_ESCTLIA_1  on ESC.ESC_TLIA   (ESC_ATRIB_VAL);
Create INDEX  ESC.IX_ESCTLIA_2  on ESC.ESC_TLIA   (ATRIB_NM);

