
  CREATE TABLE ESC.ESC_TKPG
   (	SKU_PKG_GRP_ID INTEGER NOT NULL ENABLE,
	SKU_PKG_GRP_NM VARCHAR2(30) NOT NULL ENABLE,
	PROVDR_REQD_FLG VARCHAR2(1) NOT NULL ENABLE,
	SKU_PKG_ID INTEGER NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	SKU_PKG_GRP_DESC VARCHAR2(256) NOT NULL ENABLE,
	SNGL_INSTL_REQ_FLG VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT ESCTKPG_PK PRIMARY KEY (SKU_PKG_GRP_ID)
	 ,CONSTRAINT ESCRKPG1 FOREIGN KEY (SKU_PKG_ID)
	  REFERENCES ESC.ESC_TPKG (SKU_PKG_ID) ENABLE NOVALIDATE
   ) 
;


Create INDEX  ESC.IX_ESCTKPG_1  on ESC.ESC_TKPG   (SKU_PKG_ID);

