
  CREATE TABLE ESC.ESC_TPAD
   (	VNDR_PRFL_ID INTEGER NOT NULL ENABLE,
	XML_DOC_ID INTEGER NOT NULL ENABLE,
	FILE_ACTVTY_TYP VARCHAR2(4) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	 CONSTRAINT ESCTPAD_PK PRIMARY KEY (VNDR_PRFL_ID, XML_DOC_ID, FILE_ACTVTY_TYP)
   )
;


