  CREATE TABLE ESC.ESC_TACS
   (
	AR_COMN_DTL_ID INTEGER NOT NULL ENABLE,
	COMN_SLS_BATCH_ID INTEGER NOT NULL ENABLE,
	COMN_AR_TYP VARCHAR2(4) NOT NULL ENABLE,
	ESC_CUST_ACCT_ID INTEGER NOT NULL ENABLE,
	COMN_MODL_ID INTEGER NOT NULL ENABLE,
	COMN_TRANS_POST_TS TIMESTAMP (6) NOT NULL ENABLE,
	COMN_TRANS_AMT NUMBER(9,2) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	AR_COMN_BAL_AMT NUMBER(9,2) NOT NULL ENABLE,
	AR_STAT_TYP VARCHAR2(6) NOT NULL ENABLE,
	ESC_PLAN_ID INTEGER,
	TRANS_AUDIT_ID INTEGER,
	 CONSTRAINT ESCTACS_PK PRIMARY KEY (AR_COMN_DTL_ID)
   ) 
;


Create INDEX  ESC.IX_ESCTACS_1  on ESC.ESC_TACS (ESC_CUST_ACCT_ID);
Create INDEX  ESC.IX_ESCTACS_2  on ESC.ESC_TACS (AR_COMN_BAL_AMT);
Create INDEX  ESC.IX_ESCTACS_3  on ESC.ESC_TACS (COMN_AR_TYP, COMN_SLS_BATCH_ID);
Create INDEX  ESC.IX_ESCTACS_4  on ESC.ESC_TACS (COMN_TRANS_POST_TS, COMN_AR_TYP);
Create INDEX  ESC.IX_ESCTACS_5  on ESC.ESC_TACS (TRANS_AUDIT_ID);

