
  CREATE TABLE ESC.ESC_TCAC
   (	ESC_CUST_ACCT_ID INTEGER NOT NULL ENABLE,
	ESC_PLAN_ID INTEGER NOT NULL ENABLE,
	ESC_ACCT_STAT_TYP VARCHAR2(4) NOT NULL ENABLE,
	CUST_ID NUMBER(18,0) NOT NULL ENABLE,
	ESC_ACCT_ACTV_DT DATE,
	ALL_ITEM_RTN_FLG VARCHAR2(1) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	ACCT_BAL_AMT NUMBER(9,2) NOT NULL ENABLE,
	CUST_SIGNTR_ID NUMBER(9,0),
	ESC_CA_OFFLINE VARCHAR2(1) NOT NULL ENABLE,
	AGGR_VNDR_ID NUMBER(9,0),
	AGGR_VNDR_SUBTYP VARCHAR2(3),
	 CONSTRAINT ESCTCAC_PK PRIMARY KEY (ESC_CUST_ACCT_ID)
   )
;


Create INDEX  ESC.IX_ESCTCAC_1  on ESC.ESC_TCAC (ESC_PLAN_ID ,ESC_ACCT_STAT_TYP ,REC_CREATE_TS ,AGGR_VNDR_ID);
Create INDEX  ESC.IX_ESCTCAC_2  on ESC.ESC_TCAC (CUST_ID);
Create INDEX  ESC.IX_ESCTCAC_3  on ESC.ESC_TCAC (AGGR_VNDR_ID ,AGGR_VNDR_SUBTYP);
Create INDEX  ESC.IX_ESCTCAC_4  on ESC.ESC_TCAC (REC_UPD_TS);

