
  CREATE TABLE ESC.ESC_TCMD
   (	COMN_MODL_ID INTEGER NOT NULL ENABLE,
	COMN_MODL_TYP VARCHAR2(4) NOT NULL ENABLE,
	COMN_MODL_NM VARCHAR2(30) NOT NULL ENABLE,
	TIER_CNDR_TYP VARCHAR2(4),
	TIER_PRD_TYP VARCHAR2(4),
	TIER_CNDR_PRD_NBR INTEGER,
	TIER_VAL_TYP VARCHAR2(4),
	PYMT_TLRNC_AMT NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	COMN_MODL_DESC VARCHAR2(256) NOT NULL ENABLE,
	COMN_POST_FLG VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	 CONSTRAINT ESCTCMD_PK PRIMARY KEY (COMN_MODL_ID)
   )
;


