
  CREATE TABLE ESC.ESC_TVPF
   (	VNDR_FILE_ID INTEGER NOT NULL ENABLE,
	VNDR_PYMT_XFER_TYP VARCHAR2(5),
	VNDR_PYMT_ID VARCHAR2(30) NOT NULL ENABLE,
	VNDR_PYMT_DRAW_DT DATE,
	VNDR_NET_PYMT_AMT NUMBER(9,2) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	 CONSTRAINT ESCTVPF_PK PRIMARY KEY (VNDR_FILE_ID)
	 ,CONSTRAINT ESCRVPF1 FOREIGN KEY (VNDR_FILE_ID)
	  REFERENCES ESC.ESC_TVAF (VNDR_FILE_ID) ENABLE NOVALIDATE
   ) 
;


