
  CREATE TABLE ESC.ESC_TRMD
   (	COMN_MODL_ID INTEGER NOT NULL ENABLE,
	RESID_OFFSET_TYP VARCHAR2(4) NOT NULL ENABLE,
	RESID_PRD_TYP VARCHAR2(4) NOT NULL ENABLE,
	RESID_CALC_TYP VARCHAR2(4) NOT NULL ENABLE,
	LIFE_TM_RESID_FLG VARCHAR2(1) NOT NULL ENABLE,
	MAX_RESID_PMNT_NBR INTEGER NOT NULL ENABLE,
	RESID_PRD_NBR INTEGER NOT NULL ENABLE,
	RESID_OFFSET_NBR INTEGER NOT NULL ENABLE,
	RESID_PYMT_DLR_AMT NUMBER(9,2) NOT NULL ENABLE,
	RESID_PYMT_PCT NUMBER(5,2) NOT NULL ENABLE,
	DFLT_PYMT_DLR_AMT NUMBER(9,2) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	 CONSTRAINT ESCTRMD_PK PRIMARY KEY (COMN_MODL_ID)
	 ,CONSTRAINT ESCRRMD4 FOREIGN KEY (COMN_MODL_ID)
	  REFERENCES ESC.ESC_TCMD (COMN_MODL_ID) ENABLE NOVALIDATE
   )
;


