
  CREATE TABLE ESC.ESC_TPKG
   (	SKU_PKG_ID INTEGER NOT NULL ENABLE,
	SKU_PKG_NM VARCHAR2(30) NOT NULL ENABLE,
	PKG_OWNR_TYP VARCHAR2(4) NOT NULL ENABLE,
	SKU_PKG_BEG_DT TIMESTAMP (6) NOT NULL ENABLE,
	SKU_PKG_END_DT TIMESTAMP (6) NOT NULL ENABLE,
	ESC_GRP_TYP VARCHAR2(4) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	SKU_PKG_DESC VARCHAR2(256) NOT NULL ENABLE,
	SKU_PKG_TYP VARCHAR2(4) DEFAULT 'STND' NOT NULL ENABLE,
	 CONSTRAINT ESCTPKG_PK PRIMARY KEY (SKU_PKG_ID)
	 ,CONSTRAINT ESCRPKT1 FOREIGN KEY (SKU_PKG_TYP)
	  REFERENCES ESC.ESC_TPKT (SKU_PKG_TYP) ENABLE NOVALIDATE
   ) 
;


Create INDEX  ESC.IX_ESCTPKG_1  on ESC.ESC_TPKG   (SKU_PKG_TYP);

