
  CREATE TABLE ESC.ESC_TDPM
   (	COMN_MODL_ID INTEGER NOT NULL ENABLE,
	ESC_PLAN_ID INTEGER NOT NULL ENABLE,
	COMN_DEPT_TYP VARCHAR2(4) NOT NULL ENABLE,
	POST_SKU_ID NUMBER(7,0) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	ACTV_FLG VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	 CONSTRAINT ESCTDPM_PK PRIMARY KEY (COMN_MODL_ID, ESC_PLAN_ID, COMN_DEPT_TYP)
   )
;


