
  CREATE TABLE ESC.ESC_TSTD
   (	SLS_TRANS_LN_NBR NUMBER(4,0) NOT NULL ENABLE,
	SLS_TRANS_NBR NUMBER(5,0) NOT NULL ENABLE,
	REGSTR_NBR NUMBER(3,0) NOT NULL ENABLE,
	SLS_TRANS_TS TIMESTAMP (6) NOT NULL ENABLE,
	LOC_ID NUMBER(5,0) NOT NULL ENABLE,
	ESC_LN_SEQ INTEGER NOT NULL ENABLE,
	ESC_LN_ACTVTY_TYP VARCHAR2(4) NOT NULL ENABLE,
	ESC_LN_VOID_FLG VARCHAR2(1) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	 CONSTRAINT ESCTSTD_PK PRIMARY KEY (LOC_ID, SLS_TRANS_NBR, REGSTR_NBR, SLS_TRANS_TS, SLS_TRANS_LN_NBR)
	 ,CONSTRAINT ESCRSTD1 FOREIGN KEY (LOC_ID, SLS_TRANS_NBR, REGSTR_NBR, SLS_TRANS_TS)
	  REFERENCES ESC.ESC_TSLT (LOC_ID, SLS_TRANS_NBR, REGSTR_NBR, SLS_TRANS_TS) ENABLE NOVALIDATE
   ) 
;


Create INDEX  ESC.IX_ESCTSTD_1  on ESC.ESC_TSTD   (ESC_LN_SEQ);
Create INDEX  ESC.IX_ESCTSTD_2  on ESC.ESC_TSTD   (REGSTR_NBR);
Create INDEX  ESC.IX_ESCTSTD_3  on ESC.ESC_TSTD   (SLS_TRANS_TS,LOC_ID);
Create INDEX  ESC.IX_ESCTSTD_4  on ESC.ESC_TSTD   (SLS_TRANS_NBR);
