  CREATE TABLE ESC.ESC_TARS
   (	AR_STAT_TYP VARCHAR2(6) NOT NULL ENABLE,
	AR_STAT_NM VARCHAR2(30) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	AR_STAT_DESC VARCHAR2(256) NOT NULL ENABLE,
	 CONSTRAINT ESCTARS_PK PRIMARY KEY (AR_STAT_TYP)
   )
;
