
  CREATE TABLE ESC.ESC_TCSC
   (	ESC_CUST_ACCT_ID INTEGER NOT NULL ENABLE,
	COMN_MODL_ID INTEGER NOT NULL ENABLE,
	PROC_STAT_TYP VARCHAR2(4) NOT NULL ENABLE,
	SCHD_TS TIMESTAMP (6),
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	 CONSTRAINT ESCTCSC_PK PRIMARY KEY (ESC_CUST_ACCT_ID, COMN_MODL_ID)
	 ,CONSTRAINT ESCRCSC1 FOREIGN KEY (ESC_CUST_ACCT_ID, COMN_MODL_ID)
	  REFERENCES ESC.ESC_TASC (ESC_CUST_ACCT_ID, COMN_MODL_ID) ENABLE NOVALIDATE
   ) 
;


