
  CREATE TABLE ESC.ESC_TATA
   (	COMN_AR_TYP VARCHAR2(4) NOT NULL ENABLE,
	APLY_TO_AR_TYP VARCHAR2(4) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	MANL_ADJ_FLG VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	OPR_SIGN_TYP VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT ESCTATA_PK PRIMARY KEY (COMN_AR_TYP, APLY_TO_AR_TYP)
	 ,CONSTRAINT ESCRATA1 FOREIGN KEY (COMN_AR_TYP)
	  REFERENCES ESC.ESC_TCAT (COMN_AR_TYP) ENABLE NOVALIDATE,
	 CONSTRAINT ESCRATA2 FOREIGN KEY (OPR_SIGN_TYP)
	  REFERENCES ESC.ESC_TOST (OPR_SIGN_TYP) ENABLE NOVALIDATE
   ) 
;


