
  CREATE TABLE ESC.ESC_TFAT
   (	FILE_ACTVTY_TYP VARCHAR2(4) NOT NULL ENABLE,
	FILE_ACTVTY_TYP_NM VARCHAR2(30) NOT NULL ENABLE,
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	FILE_ACTVTY_DESC VARCHAR2(256) NOT NULL ENABLE,
	JAVA_CLASS_NM VARCHAR2(256),
	FILE_TYP_HOLD_FLG VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT ESCTFAT_PK PRIMARY KEY (FILE_ACTVTY_TYP)
   )
;


