
  CREATE TABLE ESC.ESC_TASC
   (	ESC_CUST_ACCT_ID INTEGER NOT NULL ENABLE,
	COMN_MODL_ID INTEGER NOT NULL ENABLE,
	SCHD_STAT_TYP VARCHAR2(4) NOT NULL ENABLE,
	LAST_COMN_PROC_TS TIMESTAMP (6),
	REC_CREATE_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_CREATE_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_CREATE_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_PGM_ID VARCHAR2(8) NOT NULL ENABLE,
	REC_UPD_TS TIMESTAMP (6) NOT NULL ENABLE,
	REC_UPD_USR_ID VARCHAR2(8) NOT NULL ENABLE,
	 CONSTRAINT ESCTASC_PK PRIMARY KEY (ESC_CUST_ACCT_ID, COMN_MODL_ID)
	 ,CONSTRAINT ESCRASC2 FOREIGN KEY (COMN_MODL_ID)
	  REFERENCES ESC.ESC_TCMD (COMN_MODL_ID) ENABLE NOVALIDATE
   ) 
;


Create INDEX  ESC.IX_ESCTASC_1  on ESC.ESC_TASC (COMN_MODL_ID);
Create INDEX  ESC.IX_ESCTASC_2  on ESC.ESC_TASC (SCHD_STAT_TYP);

