CONNECT / AS SYSDBA


REM CREATE USER "ORACLE"  PROFILE "DEFAULT" IDENTIFIED EXTERNALLY 
    REM DEFAULT 
    REM TABLESPACE "USERS" TEMPORARY 
    REM TABLESPACE "TEMP" QUOTA 1000 K 
    REM ON USERS ACCOUNT UNLOCK;
CREATE USER "HOSTDB"  PROFILE "DEFAULT" IDENTIFIED BY "hjkbnm" 
    DEFAULT 
    TABLESPACE "APPS" TEMPORARY 
    TABLESPACE "TEMP2" 
	QUOTA UNLIMITED ON APPS 
	QUOTA UNLIMITED ON COSTING 
	QUOTA UNLIMITED ON INDX 
	ACCOUNT UNLOCK;
CREATE USER "PURCHASE/DAEMON@CS.CMU.EDU"  PROFILE "DEFAULT" 
    IDENTIFIED EXTERNALLY DEFAULT 
    TABLESPACE "USERS" 
	TEMPORARY TABLESPACE "TEMP" 
	QUOTA 100 K ON TEMP 
	QUOTA 1024 K ON USERS 
	ACCOUNT UNLOCK;
CREATE USER "PURCHASE@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "PURCHASING"  PROFILE "DEFAULT" IDENTIFIED BY 
    "1234567" DEFAULT 
    TABLESPACE "APPS" TEMPORARY 
    TABLESPACE "TEMP" 
	QUOTA UNLIMITED ON APPS 
	QUOTA 4096K ON INDX 
	ACCOUNT UNLOCK;
CREATE USER ACCOUNTING  PROFILE DEFAULT IDENTIFIED BY "yuihjk"
    DEFAULT 
    TABLESPACE "APPS" TEMPORARY 
    TABLESPACE "TEMP" 
	QUOTA UNLIMITED ON APPS 
	ACCOUNT UNLOCK;
CREATE USER "ARANYOS@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" ACCOUNT UNLOCK;
CREATE USER "BAIRD@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "BAW@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "BETHLYNN@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "BILLINGS@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "COSTING"  PROFILE "DEFAULT" IDENTIFIED EXTERNALLY 
    DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100000 K 
    ON TEMP QUOTA 100000 K 
    ON TEMP2 QUOTA UNLIMITED 
    ON USERS ACCOUNT LOCK;
CREATE USER "COSTING@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP2" QUOTA UNLIMITED 
    ON TEMP QUOTA 102400 K 
    ON TEMP2 QUOTA UNLIMITED
    ON USERS ACCOUNT UNLOCK;
CREATE USER "CPELESCA@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "DL@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "DLC@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "DOMAIN@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "ERICA3@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "GPARK@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "INDB@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED EXTERNALLY 
    DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "JHUTZ@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "KIKUCHI@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "KMB@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "KZM@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "MADD@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "MAP@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" ACCOUNT UNLOCK;
CREATE USER "MOORE@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "MOORE_ADMIN"  PROFILE "DEFAULT" IDENTIFIED BY 
    "moore" DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" ACCOUNT UNLOCK;
CREATE USER "MRILEY@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "NIKITHSE@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "PHDYE@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "RDM@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" ACCOUNT UNLOCK;
CREATE USER "RHARVARD@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "RHUMBERT@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "ROBSMITH@CS.CMU.EDU"  PROFILE "DEFAULT" 
    IDENTIFIED EXTERNALLY 
    DEFAULT TABLESPACE "USERS" 
    TEMPORARY TABLESPACE "TEMP" 
    QUOTA 100 K ON TEMP 
    QUOTA 100 K ON USERS 
    ACCOUNT UNLOCK;

CREATE USER "ROMEARA@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "ROYSE@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" 
	QUOTA 100 K ON TEMP 
	QUOTA 100K ON USERS 
	ACCOUNT LOCK;
CREATE USER "ROYSE"  PROFILE "DEFAULT" IDENTIFIED BY "1234567" 
    DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA UNLIMITED 
    ON USERS ACCOUNT LOCK;
CREATE USER "SYLVIA@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "TFAULK@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" QUOTA 100 K 
    ON TEMP QUOTA 1000 K 
    ON USERS ACCOUNT UNLOCK;
CREATE USER "TGP@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" ACCOUNT UNLOCK;
CREATE USER "WEBREPORT"  PROFILE "DEFAULT" IDENTIFIED BY 
    "Aciswr4cs" DEFAULT 
    TABLESPACE "USERS" 
	TEMPORARY TABLESPACE "TEMP" 
	QUOTA 1024 K ON TEMP 
	QUOTA 1024 K ON USERS 
	QUOTA 2048 K ON APPS 
	ACCOUNT UNLOCK;
REM /*
REM CREATE USER "YANGL@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    REM EXTERNALLY DEFAULT 
    REM TABLESPACE "USERS" 
	REM TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
REM CREATE USER "YLJ"  PROFILE "DEFAULT" IDENTIFIED BY "ylj" DEFAULT 
    REM TABLESPACE "USERS" 
	REM TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
REM */
CREATE USER "ZACK@CS.CMU.EDU"  PROFILE "DEFAULT" IDENTIFIED 
    EXTERNALLY DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" ACCOUNT UNLOCK;

ALTER USER SCOTT ACCOUNT LOCK;
commit;
exit;
