#!/bin/sh

USER=costing
HOME=/usr/${USER}
PATH=${HOME}/bin:/usr/bin:/usr/ucb:/usr/local/bin
RAMS_DB_CONNECTION=/@hostdb.fac.cs.cmu.edu

export USER HOME PATH RAMS_DB_CONNECTION

prog=`basename $0 .sh`

trap 'e=$?; exit' 1 2 15
trap 'rm -f /tmp/${prog}$$*; trap 0; exit $e' 0

cd $HOME

LOG=log/match_name.log
OLDLOG=log/match_name-old.log

find ${OLDLOG} -mtime +31 -exec mv -f ${LOG} {} \;

( \
    cd match_name;	\
    date; \
    bin/match_name.sh match_fullname ;
) >>log/match_name.log 2>&1

