SELECT ACCOUNT_STRING,
       QUALIFIED_QUERIES (FORMAT 'ZZZ,ZZZ,ZZ9'),
       (USE_SUBSTR / (QUALIFIED_QUERIES (FLOAT))) * 100 (FORMAT 'ZZ9.99') PER_SUBSTR,
       (USE_POS / (QUALIFIED_QUERIES (FLOAT))) * 100 (FORMAT 'ZZ9.99') PER_POSITION,
       (USE_LIKE / (QUALIFIED_QUERIES (FLOAT))) * 100 (FORMAT 'ZZ9.99') PER_LIKE,
       (USE_TRIM / (QUALIFIED_QUERIES (FLOAT))) * 100 (FORMAT 'ZZ9.99') PER_TRIM,
       (USE_CONCAT / (QUALIFIED_QUERIES (FLOAT))) * 100 (FORMAT 'ZZ9.99') PER_CONCAT
FROM
(
SELECT ACCOUNT_STRING,
       COUNT(*) QUALIFIED_QUERIES,
       SUM(CASE WHEN WHERE_CLAUSE LIKE '%SUBSTR%' THEN 1 ELSE 0 END) USE_SUBSTR,
       SUM(CASE WHEN WHERE_CLAUSE LIKE '%POSITION%' THEN 1 ELSE 0 END) USE_POS,
       SUM(CASE WHEN WHERE_CLAUSE LIKE '%TRIM%' THEN 1 ELSE 0 END) USE_TRIM,
       SUM(CASE WHEN WHERE_CLAUSE LIKE '%LIKE%' THEN 1 ELSE 0 END) USE_LIKE,
       SUM(CASE WHEN WHERE_CLAUSE LIKE '%||%' THEN 1 ELSE 0 END) USE_CONCAT
FROM
(
SELECT l.LOGDATE,
       -- USING TERADATA PERFORMANCE COE RECOMMENDED ACCOUNT STRING FORMAT
       SUBSTR(AcctString,5,4) ACCOUNT_STRING,
       POSITION('WHERE' IN s.sqltextinfo) WHERE_POS,
       SUBSTR(s.sqltextinfo, WHERE_POS, 32000 - WHERE_POS) WHERE_CLAUSE
FROM PDCRINFO.DBQLogTbl l,
     PDCRINFO.DBQLSqlTbl s
WHERE l.ProcID = s.ProcID
  AND l.QueryID = s.QueryID
  AND s.SqlRowNo = 1 
  AND l.LOGDATE >= CURRENT_DATE - 30
  AND WHERE_POS > 0
  AND ACCOUNT_STRING IN ('$M1$&D&H&SMEADHOC') --NOT IN ('XXXX','YYYY')
) QQ
HAVING QUALIFIED_QUERIES > 100
   AND ( USE_SUBSTR > 0 OR
         USE_POS > 0 OR
         USE_TRIM > 0 OR
         USE_LIKE > 0 OR
         USE_CONCAT > 0
       )
GROUP BY 1
) FF
ORDER BY 2 DESC,1
;
