-- Template file: $Id: td_ddl_proddb.sql,v 1.1 2009/02/17 22:05:03 A645276 Exp $
-- $Author: A645276 $
-- $Version$
----------------------------------------------------------------------------------------
--  This template file is used to generate Teradata DDLs from Oracle/SQLServer/MySQL DDLs.
--  *This template file is under source control, please do NOT edit directly.
--  *Please do NOT edit generated DDLs directly. 
--  *Usage: sqlt -f Oracle -t TTSchema --tt-conf EVAL_PERL=1 --template Oracle2TD_DDL.tt EscapeTableAll_ora.sql > td_ddl.sql
----------------------------------------------------------------------------------------
--  TODO: Add database/schema name
--  Revision History:
--      2008/12/17  LJ Yang     initial development
----------------------------------------------------------------------------------------
Drop Table PRODBBYMEADHOCDB.ESC_CUSTCST
;Drop Table PRODBBYMEADHOCDB.ESC_TACS
;Drop Table PRODBBYMEADHOCDB.ESC_TARD
;Drop Table PRODBBYMEADHOCDB.ESC_TARS
;Drop Table PRODBBYMEADHOCDB.ESC_TATA
;Drop Table PRODBBYMEADHOCDB.ESC_TCAT
;Drop Table PRODBBYMEADHOCDB.ESC_TCAC
;Drop Table PRODBBYMEADHOCDB.ESC_TCAI
;Drop Table PRODBBYMEADHOCDB.ESC_TBMD
;Drop Table PRODBBYMEADHOCDB.ESC_TCSC
;Drop Table PRODBBYMEADHOCDB.ESC_TASC
;Drop Table PRODBBYMEADHOCDB.ESC_TRMD
;Drop Table PRODBBYMEADHOCDB.ESC_TPLC
;Drop Table PRODBBYMEADHOCDB.ESC_TCMD
;Drop Table PRODBBYMEADHOCDB.ESC_TCMH
;Drop Table PRODBBYMEADHOCDB.ESC_TCPT
;Drop Table PRODBBYMEADHOCDB.ESC_TCSI
;Drop Table PRODBBYMEADHOCDB.ESC_TCTP
;Drop Table PRODBBYMEADHOCDB.ESC_TDPM
;Drop Table PRODBBYMEADHOCDB.ESC_TDPT
;Drop Table PRODBBYMEADHOCDB.ESC_TEGT
;Drop Table PRODBBYMEADHOCDB.ESC_TFAT
;Drop Table PRODBBYMEADHOCDB.ESC_TLIA
;Drop Table PRODBBYMEADHOCDB.ESC_TLNI
;Drop Table PRODBBYMEADHOCDB.ESC_TPAD
;Drop Table PRODBBYMEADHOCDB.ESC_TPAK
;Drop Table PRODBBYMEADHOCDB.ESC_TPKP
;Drop Table PRODBBYMEADHOCDB.ESC_TDVP
;Drop Table PRODBBYMEADHOCDB.ESC_TKPG
;Drop Table PRODBBYMEADHOCDB.ESC_TPKG
;Drop Table PRODBBYMEADHOCDB.ESC_TPKT
;Drop Table PRODBBYMEADHOCDB.ESC_TPLN
;Drop Table PRODBBYMEADHOCDB.ESC_TSKP
;Drop Table PRODBBYMEADHOCDB.ESC_TSTD
;Drop Table PRODBBYMEADHOCDB.ESC_TSLT
;Drop Table PRODBBYMEADHOCDB.ESC_TVNI
;Drop Table PRODBBYMEADHOCDB.ESC_TVPF
;Drop Table PRODBBYMEADHOCDB.ESC_TVAF
;Drop Table PRODBBYMEADHOCDB.ESC_TVPR
;Drop Table PRODBBYMEADHOCDB.ESC_TVPT
;Drop Table PRODBBYMEADHOCDB.ESC_TSSP
;Drop Table PRODBBYMEADHOCDB.ESC_SKUTSKU
;

Create SET Table PRODBBYMEADHOCDB.ESC_CUSTCST   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       CUST_ID       NUMERIC(18,0) NOT NULL 
       ,CUST_1ST_NM       VARCHAR(25) NOT NULL 
       ,CUST_MDL_INTL       VARCHAR(1)
       ,CUST_LAST_NM       VARCHAR(25) NOT NULL 
       ,CUST_NM_PREFIX_TYP       VARCHAR(7)
       ,CUST_ADDR_ST_NBR       VARCHAR(10)
       ,CUST_ADDR_ST_NM       VARCHAR(30) NOT NULL 
       ,CUST_ADDR_UNIT_ID       VARCHAR(10)
       ,CUST_ADDR_CITY_NM       VARCHAR(30) NOT NULL 
       ,STATE_ABBR       VARCHAR(5) NOT NULL 
       ,CUST_ADDR_ZIP       VARCHAR(7) NOT NULL 
       ,CUST_ADDR_ZIP4       VARCHAR(4)
       ,CNTRY_ID       VARCHAR(2) NOT NULL 
       ,EMAIL_ADDR_ID       VARCHAR(55)
       ,HOME_PH_AREA_NBR       VARCHAR(3)
       ,HOME_PH_NBR       VARCHAR(7) NOT NULL 
       ,WORK_PH_AREA_NBR       VARCHAR(3)
       ,WORK_PH_NBR       VARCHAR(7)
       ,WORK_PH_EXT       VARCHAR(5)
       ,EC_SENT_FLG       character(1) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,CUST_NM_SUFFIX_TYP       VARCHAR(3)
)
UNIQUE PRIMARY INDEX (   CUST_ID )
INDEX (CUST_LAST_NM,CUST_1ST_NM,CUST_ID)
INDEX (HOME_PH_NBR,CUST_LAST_NM,CUST_1ST_NM,HOME_PH_AREA_NBR)
INDEX (EC_SENT_FLG)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TACS   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       AR_COMN_DTL_ID       integer NOT NULL 
       ,COMN_SLS_BATCH_ID       integer NOT NULL 
       ,COMN_AR_TYP       VARCHAR(4) NOT NULL 
       ,ESC_CUST_ACCT_ID       integer NOT NULL 
       ,COMN_MODL_ID       integer NOT NULL 
       ,COMN_TRANS_POST_TS       TIMESTAMP(6) NOT NULL 
       ,COMN_TRANS_AMT       NUMERIC(9,2) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,AR_COMN_BAL_AMT       NUMERIC(9,2) NOT NULL 
       ,AR_STAT_TYP       VARCHAR(6) NOT NULL 
       ,ESC_PLAN_ID       integer
       ,TRANS_AUDIT_ID       integer
)
UNIQUE PRIMARY INDEX (   AR_COMN_DTL_ID )
INDEX (ESC_CUST_ACCT_ID)
INDEX (AR_COMN_BAL_AMT)
INDEX (COMN_AR_TYP,COMN_SLS_BATCH_ID)
INDEX (COMN_TRANS_POST_TS,COMN_AR_TYP)
INDEX (TRANS_AUDIT_ID)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TARD   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       AR_COMN_DTL_ID       integer NOT NULL 
       ,APLY_COMN_DTL_ID       integer NOT NULL 
       ,APLY_TRANS_AMT       NUMERIC(9,2) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   AR_COMN_DTL_ID  ,APLY_COMN_DTL_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TARS   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       AR_STAT_TYP       VARCHAR(6) NOT NULL 
       ,AR_STAT_NM       VARCHAR(30) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,AR_STAT_DESC       VARCHAR(256) NOT NULL 
)
UNIQUE PRIMARY INDEX (   AR_STAT_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TASC   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_CUST_ACCT_ID       integer NOT NULL 
       ,COMN_MODL_ID       integer NOT NULL 
       ,SCHD_STAT_TYP       VARCHAR(4) NOT NULL 
       ,LAST_COMN_PROC_TS       TIMESTAMP(6)
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
--,CONSTRAINT ESCRASC2 FOREIGN KEY (COMN_MODL_ID)
--REFERENCES PRODBBYMEADHOCDB.ESC_TCMD (COMN_MODL_ID)
--,CONSTRAINT ESCRASC3 FOREIGN KEY (SCHD_STAT_TYP)
--REFERENCES PRODBBYMEADHOCDB.ESC_TSCS (SCHD_STAT_TYP)
)
UNIQUE PRIMARY INDEX (   ESC_CUST_ACCT_ID  ,COMN_MODL_ID )
INDEX (COMN_MODL_ID)
INDEX (SCHD_STAT_TYP)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TATA   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       COMN_AR_TYP       VARCHAR(4) NOT NULL 
       ,APLY_TO_AR_TYP       VARCHAR(4) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,MANL_ADJ_FLG       VARCHAR(1) NOT NULL 
       ,OPR_SIGN_TYP       VARCHAR(1) NOT NULL 
--,CONSTRAINT ESCRATA1 FOREIGN KEY (COMN_AR_TYP)
--REFERENCES PRODBBYMEADHOCDB.ESC_TCAT (COMN_AR_TYP)
)
UNIQUE PRIMARY INDEX (   COMN_AR_TYP  ,APLY_TO_AR_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TBMD   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       COMN_MODL_ID       integer NOT NULL 
       ,CHGBK_PRD_TYP       VARCHAR(4) NOT NULL 
       ,CHGBK_PRD_NBR       integer NOT NULL 
       ,BNTY_CALC_TYP       VARCHAR(4) NOT NULL 
       ,BNTY_DLR_AMT       NUMERIC(9,2) NOT NULL 
       ,BNTY_RESRV_FLG       VARCHAR(1) NOT NULL 
       ,CHGBK_PCT       NUMERIC(5,2) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
--,CONSTRAINT ESCRBMD1 FOREIGN KEY (COMN_MODL_ID)
--REFERENCES PRODBBYMEADHOCDB.ESC_TCMD (COMN_MODL_ID)
)
UNIQUE PRIMARY INDEX (   COMN_MODL_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TCAC   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_CUST_ACCT_ID       integer NOT NULL 
       ,ESC_PLAN_ID       integer NOT NULL 
       ,ESC_ACCT_STAT_TYP       VARCHAR(4) NOT NULL 
       ,CUST_ID       NUMERIC(18,0) NOT NULL 
       ,ESC_ACCT_ACTV_DT       DATE
       ,ALL_ITEM_RTN_FLG       VARCHAR(1) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,ACCT_BAL_AMT       NUMERIC(9,2) NOT NULL 
       ,CUST_SIGNTR_ID       NUMERIC(9,0)
       ,ESC_CA_OFFLINE       VARCHAR(1) NOT NULL 
       ,AGGR_VNDR_ID       NUMERIC(9,0)
       ,AGGR_VNDR_SUBTYP       VARCHAR(3)
)
UNIQUE PRIMARY INDEX (   ESC_CUST_ACCT_ID )
INDEX (ESC_PLAN_ID,ESC_ACCT_STAT_TYP,REC_CREATE_TS,AGGR_VNDR_ID)
INDEX (CUST_ID)
INDEX (AGGR_VNDR_ID,AGGR_VNDR_SUBTYP)
INDEX (REC_UPD_TS)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TCAI   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_CUST_ACCT_ID       integer NOT NULL 
       ,ESC_LN_SEQ       integer NOT NULL 
       ,ESC_LN_STAT_TYP       VARCHAR(4) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
)
UNIQUE PRIMARY INDEX (   ESC_CUST_ACCT_ID  ,ESC_LN_SEQ )
INDEX (ESC_LN_SEQ)
INDEX (REC_UPD_TS)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TCAT   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       COMN_AR_TYP       VARCHAR(4) NOT NULL 
       ,COMN_AR_TYP_NM       VARCHAR(30) NOT NULL 
       ,OPR_SIGN_TYP       VARCHAR(1) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,COMN_AR_TYP_DESC       VARCHAR(256) NOT NULL 
)
UNIQUE PRIMARY INDEX (   COMN_AR_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TCMD   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       COMN_MODL_ID       integer NOT NULL 
       ,COMN_MODL_TYP       VARCHAR(4) NOT NULL 
       ,COMN_MODL_NM       VARCHAR(30) NOT NULL 
       ,TIER_CNDR_TYP       VARCHAR(4)
       ,TIER_PRD_TYP       VARCHAR(4)
       ,TIER_CNDR_PRD_NBR       integer
       ,TIER_VAL_TYP       VARCHAR(4)
       ,PYMT_TLRNC_AMT       NUMERIC(9,2) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,COMN_MODL_DESC       VARCHAR(256) NOT NULL 
       ,COMN_POST_FLG       VARCHAR(1) NOT NULL 
)
UNIQUE PRIMARY INDEX (   COMN_MODL_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TCMH   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_CUST_ACCT_ID       integer NOT NULL 
       ,ESC_COMM_HIST_NBR       integer NOT NULL 
       ,FILE_ACTVTY_TYP       VARCHAR(4) NOT NULL 
       ,ESC_COMM_TS       TIMESTAMP(6)
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,VNDR_ID       NUMERIC(9,0)
       ,VNDR_SUBTYP       VARCHAR(3)
       ,ESC_LN_SEQ       integer
)
UNIQUE PRIMARY INDEX (   ESC_CUST_ACCT_ID  ,ESC_COMM_HIST_NBR  ,FILE_ACTVTY_TYP )
INDEX (ESC_COMM_TS)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TCPT   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       CHGBK_PRD_TYP       VARCHAR(4) NOT NULL 
       ,CHGBK_PRD_TYP_NM       VARCHAR(30) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,CHGBK_PRD_TYP_DESC       VARCHAR(256) NOT NULL 
)
UNIQUE PRIMARY INDEX (   CHGBK_PRD_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TCSC   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_CUST_ACCT_ID       integer NOT NULL 
       ,COMN_MODL_ID       integer NOT NULL 
       ,PROC_STAT_TYP       VARCHAR(4) NOT NULL 
       ,SCHD_TS       TIMESTAMP(6)
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
--,CONSTRAINT ESCRCSC1 FOREIGN KEY (ESC_CUST_ACCT_ID,COMN_MODL_ID)
--REFERENCES PRODBBYMEADHOCDB.ESC_TASC (ESC_CUST_ACCT_ID,COMN_MODL_ID)
)
UNIQUE PRIMARY INDEX (   ESC_CUST_ACCT_ID  ,COMN_MODL_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TCSI   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_CUST_ACCT_ID       integer NOT NULL 
       ,INST_1ST_NM       VARCHAR(25)
       ,INST_MDL_INTL       VARCHAR(1)
       ,INST_LAST_NM       VARCHAR(25)
       ,INST_NM_PREFIX_TYP       VARCHAR(7)
       ,INST_NM_SUFFIX_TYP       VARCHAR(3)
       ,INST_ADDR_ST_NBR       VARCHAR(10)
       ,INST_ADDR_ST_NM       VARCHAR(30)
       ,INST_ADDR_UNIT_ID       VARCHAR(10)
       ,INST_ADDR_CITY_NM       VARCHAR(30)
       ,INST_STATE_ABBR       VARCHAR(5)
       ,INST_ADDR_ZIP       VARCHAR(7)
       ,INST_ADDR_ZIP4       VARCHAR(4)
       ,INST_CNTRY_ID       VARCHAR(2)
       ,INST_HOME_PH_AREA       VARCHAR(3)
       ,INST_HOME_PH_NBR       VARCHAR(7)
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       --,PCI_CRCARD_TYPE       VARCHAR(1)
       ,EMAIL_ADDR_ID       VARCHAR(55)
       ,WORK_PH_AREA_NBR       VARCHAR(3)
       ,WORK_PH_NBR       VARCHAR(7)
       ,WORK_PH_EXT       VARCHAR(5)
       ,COMN_DEPT_TYP       VARCHAR(4) NOT NULL 
       ,CRCD_AUTH_ID       VARCHAR(16)
       ,CUST_RAC_USR_ID       VARCHAR(30)
       ,CUST_RAC_PSWD_TXT       VARCHAR(8)
       ,LANG_LCLE_ID       NUMERIC(10,0)
       ,CRCARD_ACCT_ID       VARBYTE(32)
       ,CRCARD_EXP_YEAR       VARBYTE(32)
       ,CRCARD_EXP_MNTH       VARBYTE(32)
       ,CRCARD_1ST_NM       VARBYTE(32)
       ,CRCARD_LAST_NM       VARBYTE(32)
       ,CRCARD_MDL_INTL       VARBYTE(32)
       ,CRCARD_TYPE       VARBYTE(16)
       ,CVRD_SKU_ID       NUMERIC(7,0)
)
UNIQUE PRIMARY INDEX (   ESC_CUST_ACCT_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TCTP   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       COMN_MODL_TYP       VARCHAR(4) NOT NULL 
       ,COMN_MODL_TYP_NM       VARCHAR(30) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,COMN_MODL_TYP_DESC       VARCHAR(256) NOT NULL 
)
UNIQUE PRIMARY INDEX (   COMN_MODL_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TDPM   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       COMN_MODL_ID       integer NOT NULL 
       ,ESC_PLAN_ID       integer NOT NULL 
       ,COMN_DEPT_TYP       VARCHAR(4) NOT NULL 
       ,POST_SKU_ID       NUMERIC(7,0) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,ACTV_FLG       VARCHAR(1) NOT NULL 
)
UNIQUE PRIMARY INDEX (   COMN_MODL_ID  ,ESC_PLAN_ID  ,COMN_DEPT_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TDPT   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       COMN_DEPT_TYP       VARCHAR(4) NOT NULL 
       ,COMN_DEPT_NM       VARCHAR(30) NOT NULL 
       ,COMN_DEPT_DESC       VARCHAR(255) NOT NULL 
       ,COMN_DEPT_ACTV_FLG       VARCHAR(1) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
)
UNIQUE PRIMARY INDEX (   COMN_DEPT_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TDVP   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SKU_PKG_GRP_ID       integer NOT NULL 
       ,VNDR_ID       NUMERIC(9,0) NOT NULL 
       ,VNDR_SUBTYP       VARCHAR(3) NOT NULL 
       ,SKU_ID       NUMERIC(7,0) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
--,CONSTRAINT ESCRDVP1 FOREIGN KEY (SKU_PKG_GRP_ID)
--REFERENCES PRODBBYMEADHOCDB.ESC_TKPG (SKU_PKG_GRP_ID)
)
UNIQUE PRIMARY INDEX (   SKU_PKG_GRP_ID  ,VNDR_ID  ,VNDR_SUBTYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TEGT   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       TRANS_AUDIT_ID       integer NOT NULL 
       ,SLS_TRANS_NBR       NUMERIC(5,0) NOT NULL 
       ,REGSTR_NBR       NUMERIC(3,0) NOT NULL 
       ,SLS_TRANS_TS       TIMESTAMP(6) NOT NULL 
       ,LOC_ID       NUMERIC(5,0) NOT NULL 
       ,AUDIT_TYP       VARCHAR(4) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,COMN_AR_TYP       VARCHAR(4)
       ,POST_SKU_ID       NUMERIC(7,0)
       ,SALE_AMT       NUMERIC(9,2)
       ,GL_CD       VARCHAR(6)
       ,SALE_POST_TS       TIMESTAMP(6)
       ,SLS_ADT_PCSD_STAT_TYP       VARCHAR(4) NOT NULL 
       ,SLS_ADT_PRCS_MC_NM       VARCHAR(10)
       ,CC_FEED_PCSD_STAT_TYP       VARCHAR(4) NOT NULL 
)
UNIQUE PRIMARY INDEX (   TRANS_AUDIT_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TFAT   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       FILE_ACTVTY_TYP       VARCHAR(4) NOT NULL 
       ,FILE_ACTVTY_TYP_NM       VARCHAR(30) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,FILE_ACTVTY_DESC       VARCHAR(256) NOT NULL 
       ,JAVA_CLASS_NM       VARCHAR(256)
       ,FILE_TYP_HOLD_FLG       VARCHAR(1) NOT NULL 
)
UNIQUE PRIMARY INDEX (   FILE_ACTVTY_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TKPG   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SKU_PKG_GRP_ID       integer NOT NULL 
       ,SKU_PKG_GRP_NM       VARCHAR(30) NOT NULL 
       ,PROVDR_REQD_FLG       VARCHAR(1) NOT NULL 
       ,SKU_PKG_ID       integer NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,SKU_PKG_GRP_DESC       VARCHAR(256) NOT NULL 
       ,SNGL_INSTL_REQ_FLG       VARCHAR(1) NOT NULL 
--,CONSTRAINT ESCRKPG1 FOREIGN KEY (SKU_PKG_ID)
--REFERENCES PRODBBYMEADHOCDB.ESC_TPKG (SKU_PKG_ID)
)
UNIQUE PRIMARY INDEX (   SKU_PKG_GRP_ID )
INDEX (SKU_PKG_ID)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TLIA   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_LN_SEQ       integer NOT NULL 
       ,ATRIB_NM       VARCHAR(10) NOT NULL 
       ,ESC_ATRIB_VAL       VARCHAR(100) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   ESC_LN_SEQ  ,ATRIB_NM )
INDEX (ESC_ATRIB_VAL)
INDEX (ATRIB_NM)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TLNI   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_LN_SEQ       integer NOT NULL 
       ,ESC_LN_SKU_ID       NUMERIC(7,0) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,ORIG_SLS_TRANS_NBR       NUMERIC(5,0) NOT NULL 
       ,ORIG_LOC_ID       NUMERIC(5,0) NOT NULL 
       ,ORIG_REGSTR_NBR       NUMERIC(3,0) NOT NULL 
       ,ORIG_SLS_TRANS_TS       TIMESTAMP(6) NOT NULL 
       ,SLS_TRANS_LN_AMT       NUMERIC(9,2) NOT NULL 
)
UNIQUE PRIMARY INDEX (   ESC_LN_SEQ )
INDEX (ORIG_LOC_ID,ORIG_SLS_TRANS_NBR,ORIG_REGSTR_NBR,ORIG_SLS_TRANS_TS)
INDEX (ESC_LN_SKU_ID)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TPAD   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       VNDR_PRFL_ID       integer NOT NULL 
       ,XML_DOC_ID       integer NOT NULL 
       ,FILE_ACTVTY_TYP       VARCHAR(4) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   VNDR_PRFL_ID  ,XML_DOC_ID  ,FILE_ACTVTY_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TPAK   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SKU_ID       NUMERIC(7,0) NOT NULL 
       ,ESC_PLAN_ID       integer NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   SKU_ID  ,ESC_PLAN_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TPKG   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SKU_PKG_ID       integer NOT NULL 
       ,SKU_PKG_NM       VARCHAR(30) NOT NULL 
       ,PKG_OWNR_TYP       VARCHAR(4) NOT NULL 
       ,SKU_PKG_BEG_DT       TIMESTAMP(6) NOT NULL 
       ,SKU_PKG_END_DT       TIMESTAMP(6) NOT NULL 
       ,ESC_GRP_TYP       VARCHAR(4) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,SKU_PKG_DESC       VARCHAR(256) NOT NULL 
       ,SKU_PKG_TYP       VARCHAR(4) NOT NULL 
--,CONSTRAINT ESCRPKT1 FOREIGN KEY (SKU_PKG_TYP)
--REFERENCES PRODBBYMEADHOCDB.ESC_TPKT (SKU_PKG_TYP)
)
UNIQUE PRIMARY INDEX (   SKU_PKG_ID )
INDEX (SKU_PKG_TYP)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TPKP   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SKU_PKG_ID       integer NOT NULL 
       ,SKU_ID       NUMERIC(7,0) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   SKU_PKG_ID  ,SKU_ID )
INDEX (SKU_ID)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TPKT   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SKU_PKG_TYP       VARCHAR(4) NOT NULL 
       ,SKU_PKG_TYP_NM       VARCHAR(30) NOT NULL 
       ,SKU_PKG_TYP_DESC       VARCHAR(256) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   SKU_PKG_TYP )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TPLC   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_PLAN_ID       integer NOT NULL 
       ,COMN_MODL_ID       integer NOT NULL 
       ,PLAN_COMN_BEG_TS       TIMESTAMP(6) NOT NULL 
       ,PLAN_COMN_END_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,SKU_ID       NUMERIC(7,0)
--,CONSTRAINT ESCRPLC1 FOREIGN KEY (COMN_MODL_ID)
--REFERENCES PRODBBYMEADHOCDB.ESC_TCMD (COMN_MODL_ID)
--,CONSTRAINT ESCRPLC2 FOREIGN KEY (ESC_PLAN_ID)
--REFERENCES PRODBBYMEADHOCDB.ESC_TPLN (ESC_PLAN_ID)
)
UNIQUE PRIMARY INDEX (   ESC_PLAN_ID  ,COMN_MODL_ID )
INDEX (COMN_MODL_ID)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TPLN   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ESC_PLAN_ID       integer NOT NULL 
       ,VNDR_ID       NUMERIC(9,0) NOT NULL 
       ,VNDR_SUBTYP       VARCHAR(3) NOT NULL 
       ,ESC_PLAN_NM       VARCHAR(30) NOT NULL 
       ,PLAN_ACTV_FLG       VARCHAR(1) NOT NULL 
       ,MULT_PRIM_SKU_FLG       VARCHAR(1) NOT NULL 
       ,ESC_GRP_TYP       VARCHAR(4) NOT NULL 
       ,VNDR_PLAN_ID       VARCHAR(30) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,ESC_PLAN_DESC       VARCHAR(256)
       ,ESC_PLAN_XPTN_TYP       VARCHAR(4) NOT NULL 
       ,CUST_PLAN_XPTN_TYP       VARCHAR(4) NOT NULL 
       ,ESC_PLAN_NRTC_FLG       VARCHAR(1) NOT NULL 
       ,AVAIL_OFFLN_FLG       VARCHAR(1) NOT NULL 
       ,SEC_VNDR_PLAN_ID       VARCHAR(50)
)
UNIQUE PRIMARY INDEX (   ESC_PLAN_ID )
INDEX (VNDR_ID,VNDR_SUBTYP)
INDEX (ESC_GRP_TYP)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TRMD   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       COMN_MODL_ID       integer NOT NULL 
       ,RESID_OFFSET_TYP       VARCHAR(4) NOT NULL 
       ,RESID_PRD_TYP       VARCHAR(4) NOT NULL 
       ,RESID_CALC_TYP       VARCHAR(4) NOT NULL 
       ,LIFE_TM_RESID_FLG       VARCHAR(1) NOT NULL 
       ,MAX_RESID_PMNT_NBR       integer NOT NULL 
       ,RESID_PRD_NBR       integer NOT NULL 
       ,RESID_OFFSET_NBR       integer NOT NULL 
       ,RESID_PYMT_DLR_AMT       NUMERIC(9,2) NOT NULL 
       ,RESID_PYMT_PCT       NUMERIC(5,2) NOT NULL 
       ,DFLT_PYMT_DLR_AMT       NUMERIC(9,2) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
--,CONSTRAINT ESCRRMD4 FOREIGN KEY (COMN_MODL_ID)
--REFERENCES PRODBBYMEADHOCDB.ESC_TCMD (COMN_MODL_ID)
)
UNIQUE PRIMARY INDEX (   COMN_MODL_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TSKP   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SKU_PKG_GRP_ID       integer NOT NULL 
       ,SKU_ID       NUMERIC(7,0) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   SKU_PKG_GRP_ID  ,SKU_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TSLT   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SLS_TRANS_NBR       NUMERIC(5,0) NOT NULL 
       ,REGSTR_NBR       NUMERIC(3,0) NOT NULL 
       ,SLS_TRANS_TS       TIMESTAMP(6) NOT NULL 
       ,LOC_ID       NUMERIC(5,0) NOT NULL 
       ,ESC_TRANS_SRC_TYP       VARCHAR(4) NOT NULL 
       ,ESC_TRANS_VOID_FLG       VARCHAR(1) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   LOC_ID  ,SLS_TRANS_NBR  ,REGSTR_NBR  ,SLS_TRANS_TS )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TSTD   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SLS_TRANS_LN_NBR       NUMERIC(4,0) NOT NULL 
       ,SLS_TRANS_NBR       NUMERIC(5,0) NOT NULL 
       ,REGSTR_NBR       NUMERIC(3,0) NOT NULL 
       ,SLS_TRANS_TS       TIMESTAMP(6) NOT NULL 
       ,LOC_ID       NUMERIC(5,0) NOT NULL 
       ,ESC_LN_SEQ       integer NOT NULL 
       ,ESC_LN_ACTVTY_TYP       VARCHAR(4) NOT NULL 
       ,ESC_LN_VOID_FLG       VARCHAR(1) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
--,CONSTRAINT ESCRSTD1 FOREIGN KEY (LOC_ID,SLS_TRANS_NBR,REGSTR_NBR,SLS_TRANS_TS)
--REFERENCES PRODBBYMEADHOCDB.ESC_TSLT (LOC_ID,SLS_TRANS_NBR,REGSTR_NBR,SLS_TRANS_TS)
)
UNIQUE PRIMARY INDEX (   LOC_ID  ,SLS_TRANS_NBR  ,REGSTR_NBR  ,SLS_TRANS_TS  ,SLS_TRANS_LN_NBR )
INDEX (ESC_LN_SEQ)
INDEX (REGSTR_NBR)
INDEX (SLS_TRANS_TS,LOC_ID)
INDEX (SLS_TRANS_NBR)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TVAF   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       VNDR_FILE_ID       integer NOT NULL 
       ,VNDR_ID       NUMERIC(9,0)
       ,VNDR_SUBTYP       VARCHAR(3)
       ,ARCHIVE_CMPUTR_NM       VARCHAR(30) NOT NULL 
       ,VNDR_FILE_STAT       VARCHAR(6) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,ARCHIVE_FILE_NM       VARCHAR(256) NOT NULL 
)
UNIQUE PRIMARY INDEX (   VNDR_FILE_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TVNI   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       VNDR_ID       NUMERIC(9,0) NOT NULL 
       ,VNDR_SUBTYP       VARCHAR(3) NOT NULL 
       ,FISC_TYP_ID       integer NOT NULL 
       ,VNDR_PRFL_ID       integer NOT NULL 
       ,ACTV_PH_AREA_NBR       VARCHAR(3) NOT NULL 
       ,ACTV_PH_NBR       VARCHAR(7) NOT NULL 
       ,ACTV_PH_EXT       VARCHAR(5)
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,ESC_VNDR_POS_TXT       VARCHAR(256) NOT NULL 
)
UNIQUE PRIMARY INDEX (   VNDR_ID  ,VNDR_SUBTYP )
INDEX (FISC_TYP_ID)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TVPF   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       VNDR_FILE_ID       integer NOT NULL 
       ,VNDR_PYMT_XFER_TYP       VARCHAR(5)
       ,VNDR_PYMT_ID       VARCHAR(30) NOT NULL 
       ,VNDR_PYMT_DRAW_DT       DATE
       ,VNDR_NET_PYMT_AMT       NUMERIC(9,2) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
--,CONSTRAINT ESCRVPF1 FOREIGN KEY (VNDR_FILE_ID)
--REFERENCES PRODBBYMEADHOCDB.ESC_TVAF (VNDR_FILE_ID)
)
UNIQUE PRIMARY INDEX (   VNDR_FILE_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TVPR   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       VNDR_PRFL_ID       integer NOT NULL 
       ,VNDR_ID       NUMERIC(9,0) NOT NULL 
       ,VNDR_SUBTYP       VARCHAR(3) NOT NULL 
       ,FILE_PRFL_TYP       VARCHAR(4) NOT NULL 
       ,FILE_LAYOT_TYP       VARCHAR(4) NOT NULL 
       ,TRANSPT_PROTCL_TYP       VARCHAR(5) NOT NULL 
       ,DELMT_TXT       VARCHAR(1)
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,XFER_USR_ID       VARCHAR(20)
       ,XFER_PSWD_TXT       VARCHAR(20)
       ,GRFX_EC_TYPE       VARCHAR(3)
       ,EC_RAW_DATA_FLG       VARCHAR(1) NOT NULL 
       ,EC_GRFX_FILE_FLG       VARCHAR(1) NOT NULL 
       ,EC_ECNTR_FLG       VARCHAR(1) NOT NULL 
       ,EC_SSN_FLG       VARCHAR(1) NOT NULL 
       ,EC_SEC_ADDR_FLG       VARCHAR(1) NOT NULL 
       ,EC_SIGNTR_FLG       VARCHAR(1) NOT NULL 
       ,EC_CRDT_INFO_FLG       VARCHAR(1) NOT NULL 
       ,VNDR_ECNTR_FILE       VARCHAR(12)
       ,XFER_XSL_FILE_NM       VARCHAR(100)
       ,TRNSPT_URL_TXT       VARCHAR(256)
       ,TRNSPT_DIR_TXT       VARCHAR(256)
       ,VNDR_HDR_SIZE       integer
       ,VNDR_DT_FORMAT       VARCHAR(25)
       ,EC_EMAIL_REQ_FLG       VARCHAR(1) NOT NULL 
       ,EC_SSN_REQ_FLG       VARCHAR(1) NOT NULL 
       ,PLAN_SEL_REQD_FLG       VARCHAR(1) NOT NULL 
       ,ATTRB_REQD_FLG       VARCHAR(1) NOT NULL 
       ,EC_SEC_INFO_FLG       VARCHAR(1) NOT NULL 
       ,INCL_ALL_HDWR_FLG       VARCHAR(1) NOT NULL 
       ,DUP_ACCT_INCL_FLG       VARCHAR(1) NOT NULL 
       ,AGGR_VNDR_FLG       VARCHAR(1) NOT NULL 
       ,CUST_SEL_REQ_FLG       VARCHAR(1) NOT NULL 
       ,EC_WORK_PH_REQ_FLG       VARCHAR(1) NOT NULL 
       ,EC_WORK_PH_DIS_FLG       VARCHAR(1) NOT NULL 
       ,EC_EMAIL_DIS_FLG       VARCHAR(1) NOT NULL 
       ,COMN_DEPT_DIS_FLG       VARCHAR(1) NOT NULL 
       ,SYS_EXCP_RSLN_FLG       VARCHAR(1) NOT NULL 
       ,ESC_RAC_ENBL_FLG       VARCHAR(1) NOT NULL 
       ,ESC_RAC_OFFLN_CDE       VARCHAR(1) NOT NULL 
       ,EXCH_ENBL_FLG       VARCHAR(1) NOT NULL 
       ,B2B_SFWR_VER_ID       VARCHAR(10) NOT NULL 
       ,INVL_ACCT_AUTO_CMPLT_FLG       VARCHAR(1) NOT NULL 
)
UNIQUE PRIMARY INDEX (   VNDR_PRFL_ID )
INDEX (VNDR_ID,VNDR_SUBTYP)
;
Create SET Table PRODBBYMEADHOCDB.ESC_TVPT   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       ATRIB_PRFL_ID       integer NOT NULL 
       ,VNDR_ATRIB_TYP       VARCHAR(10) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   ATRIB_PRFL_ID  ,VNDR_ATRIB_TYP )
INDEX (VNDR_ATRIB_TYP)
;
Create SET Table PRODBBYMEADHOCDB.ESC_SKUTSKU   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SKU_ID       NUMERIC(7,0) NOT NULL 
       ,SKU_DESC       VARCHAR(30) NOT NULL 
       ,SKU_MFG_MODEL_ID       VARCHAR(10) NOT NULL 
       ,SUBCLASS_ID       NUMERIC(4,0) NOT NULL 
       ,CLASS_ID       NUMERIC(4,0) NOT NULL 
       ,DEPT_ID       NUMERIC(3,0) NOT NULL 
       ,SKU_ACTV_FLG       VARCHAR(1) NOT NULL 
       ,PRIM_VNDR_ID       NUMERIC(9,0) NOT NULL 
       ,REC_CREATE_DT       DATE NOT NULL 
       ,REC_UPD_PGM_TS       TIMESTAMP(6) NOT NULL 
       ,REC_UPD_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_UPD_PGM_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   SKU_ID )
;
Create SET Table PRODBBYMEADHOCDB.ESC_TSSP   ,NO FALLBACK , NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT
(
       SKU_PKG_GRP_ID       NUMERIC(38,0) NOT NULL 
       ,DEPT_ID       NUMERIC(3,0) NOT NULL 
       ,CLASS_ID       NUMERIC(4,0) NOT NULL 
       ,SUBCLASS_ID       NUMERIC(4,0) NOT NULL 
       ,REC_CREATE_TS       TIMESTAMP(6) NOT NULL 
       ,REC_CREATE_USR_ID       VARCHAR(8) NOT NULL 
       ,REC_CREATE_PGM_ID       VARCHAR(8) NOT NULL 
)
UNIQUE PRIMARY INDEX (   SKU_PKG_GRP_ID  ,DEPT_ID  ,CLASS_ID  ,SUBCLASS_ID )
;
