spool by_andrewid.lst
select
	andrew_id
	||','||'"'||emp_name||'"'
	||','||emp_num
  from hostdb.emp
 where upper(andrew_id) in 
(
'SB56' ,'LORRIE' ,'GUNA' ,'ALM3' ,'ALF' ,'SB21' ,'JT1X' ,'DAWNSONG' ,'TRB' ,'YCAI' ,'ADRIAN'
,'BFALSAFI' ,'SEITZ' ,'ADAMCHIK' ,'RAVI' ,'SUTNER' ,'KLATZKY' ,'AG' ,'VALDES' ,'JDOLAN' ,'DS5L'
,'JOHNZ' ,'SCOTT' ,'JLM' ,'TAISLEE' ,'MWS' ,'CFROMME' ,'DL5J' ,'TG1F' ,'HPM' ,'RT30'
,'HERBSLEB' ,'KUFFNER' ,'CFRIEZE' ,'RUDICH' ,'SHIMADA' ,'ROTH' ,'JA0S' ,'LEW' ,'RBD' ,'MSHAW'
,'FARKAS' ,'AGN' ,'MBLUM' ,'ML23' ,'GARTH' ,'CL' ,'LATANYA' ,'MARKD3' ,'OLSTON'
,'RMARTIN' ,'JR4G' ,'BR' ,'DJAMES' ,'JCOHN' ,'FEDDER' ,'DROH' ,'ME51' ,'LARRY' ,'ALDRICH'
,'CJL' ,'RHOLLIS' ,'DST' ,'MM3X' ,'CP3A' ,'YANXI' ,'BOURNE' ,'WCOHEN' ,'NS1I' ,'ST1T' ,'REITER'
,'CRARY' ,'BF1H' ,'MURPHY' ,'JS35' ,'PL1A' ,'BJ07' ,'BROWNING' ,'BDIAS' ,'ILLAH' ,'DA1V'
,'RMAXION' ,'DMM' ,'IAINM' ,'JCM' ,'CHOSET' ,'VA0E' ,'RWH' ,'BAKER3' ,'SANDHOLM'
,'GM2F' ,'AVRIM' ,'HARCHOL' ,'AWB' ,'HS1D' ,'YOKY' ,'SCHEMPF' ,'CRIVIERE' ,'LEVIN'
,'BMM' ,'SRINI' ,'JW35' ,'RAJKUMAR' ,'NPOLLARD' ,'RCOLLINS' ,'SFUSSELL' ,'BJ0K' ,'RB3L'
,'PR1G' ,'CHRISTEL' ,'HUDSON' ,'RIZZI' ,'WW0T' ,'JY22' ,'FP' ,'DURAND' ,'NATASSA'
,'AK3H' ,'JMOSTOW' ,'TANJAS' ,'GG25' ,'DW0S' ,'KRAUT' ,'STVOGEL' ,'HZHANG' ,'PAUSCH'
,'BM1X' ,'CHRISTOS' ,'JUDITHKS' ,'RR2L' ,'SETHG' ,'SSMITH' ,'MOWRY' ,'JEFF4' ,'JS89'
,'SCHERLIS' ,'RSIMMONS' ,'STHAYER' ,'FORLIZZI' ,'JHM' ,'KIESLER' ,'MAX' ,'EN09' ,'YIMING'
,'TERUKO' ,'CARLEY' ,'JKH' ,'CGA' ,'AH1Z' ,'ALON' ,'OA02' ,'LBLUM' ,'KK1U'
,'AWM' ,'KHOSLA' ,'EC10' ,'THORPE' ,'JBARES' ,'PETER2' ,'JOHN3' ,'GB1Y' ,'HH11'
,'MHEBERT' ,'SYCARA' ,'DG4D' ,'AR28' ,'SATYA' ,'MITCHELL' ,'RR0S' ,'MV10' ,'CALLAN'
,'STIDLE' ,'WAIBEL' ,'WACTLAR' ,'SEF' ,'STENTZ' ,'KANADE' ,'DS1P' ,'JC6O' ,'WS1J'
,'MD3S' ,'RR6D' ,'WEHRER' ,'AS11' ,'JOHNA' ,'VSA' ,'BATAVIA' ,'DAN' ,'JACOBO'
,'CARROLL2' ,'COCHRAN' ,'EC15' ,'COPETAS' ,'RJC' ,'DE0U' ,'BILL' ,'JE0K' ,'DE66'
,'EVENSON' ,'FARBER' ,'FIENBERG' ,'FREDKIN' ,'MHAPPOLD' ,'HEFLEY' ,'TLH' ,'IKEUCHI' ,'PAMELAJ'
,'GKESDEN' ,'MK6X' ,'JKUBICA' ,'JKUKAWA' ,'SM38' ,'JOEMERTZ' ,'BASSOON' ,'TNG' ,'PATTIS'
,'PLAUT' ,'JR2U' ,'ROSSO' ,'SCERRI' ,'SCHANK' ,'SCHEINES' ,'TS1S' ,'SHAMOS' ,'JIANBOS'
,'MSITTI' ,'JS6W' ,'DSLATER' ,'DSA0' ,'MJS' ,'RS9F' ,'TYGAR' ,'AV0M'
)
union
select 
	user_name
	||','||'"'||full_name||'"'
	||','||employee_number
  from hostdb.acl_users
 where user_name in
(
'SB56' ,'LORRIE' ,'GUNA' ,'ALM3' ,'ALF' ,'SB21' ,'JT1X' ,'DAWNSONG' ,'TRB' ,'YCAI' ,'ADRIAN'
,'BFALSAFI' ,'SEITZ' ,'ADAMCHIK' ,'RAVI' ,'SUTNER' ,'KLATZKY' ,'AG' ,'VALDES' ,'JDOLAN' ,'DS5L'
,'JOHNZ' ,'SCOTT' ,'JLM' ,'TAISLEE' ,'MWS' ,'CFROMME' ,'DL5J' ,'TG1F' ,'HPM' ,'RT30'
,'HERBSLEB' ,'KUFFNER' ,'CFRIEZE' ,'RUDICH' ,'SHIMADA' ,'ROTH' ,'JA0S' ,'LEW' ,'RBD' ,'MSHAW'
,'FARKAS' ,'AGN' ,'MBLUM' ,'ML23' ,'GARTH' ,'CL' ,'LATANYA' ,'MARKD3' ,'OLSTON'
,'RMARTIN' ,'JR4G' ,'BR' ,'DJAMES' ,'JCOHN' ,'FEDDER' ,'DROH' ,'ME51' ,'LARRY' ,'ALDRICH'
,'CJL' ,'RHOLLIS' ,'DST' ,'MM3X' ,'CP3A' ,'YANXI' ,'BOURNE' ,'WCOHEN' ,'NS1I' ,'ST1T' ,'REITER'
,'CRARY' ,'BF1H' ,'MURPHY' ,'JS35' ,'PL1A' ,'BJ07' ,'BROWNING' ,'BDIAS' ,'ILLAH' ,'DA1V'
,'RMAXION' ,'DMM' ,'IAINM' ,'JCM' ,'CHOSET' ,'VA0E' ,'RWH' ,'BAKER3' ,'SANDHOLM'
,'GM2F' ,'AVRIM' ,'HARCHOL' ,'AWB' ,'HS1D' ,'YOKY' ,'SCHEMPF' ,'CRIVIERE' ,'LEVIN'
,'BMM' ,'SRINI' ,'JW35' ,'RAJKUMAR' ,'NPOLLARD' ,'RCOLLINS' ,'SFUSSELL' ,'BJ0K' ,'RB3L'
,'PR1G' ,'CHRISTEL' ,'HUDSON' ,'RIZZI' ,'WW0T' ,'JY22' ,'FP' ,'DURAND' ,'NATASSA'
,'AK3H' ,'JMOSTOW' ,'TANJAS' ,'GG25' ,'DW0S' ,'KRAUT' ,'STVOGEL' ,'HZHANG' ,'PAUSCH'
,'BM1X' ,'CHRISTOS' ,'JUDITHKS' ,'RR2L' ,'SETHG' ,'SSMITH' ,'MOWRY' ,'JEFF4' ,'JS89'
,'SCHERLIS' ,'RSIMMONS' ,'STHAYER' ,'FORLIZZI' ,'JHM' ,'KIESLER' ,'MAX' ,'EN09' ,'YIMING'
,'TERUKO' ,'CARLEY' ,'JKH' ,'CGA' ,'AH1Z' ,'ALON' ,'OA02' ,'LBLUM' ,'KK1U'
,'AWM' ,'KHOSLA' ,'EC10' ,'THORPE' ,'JBARES' ,'PETER2' ,'JOHN3' ,'GB1Y' ,'HH11'
,'MHEBERT' ,'SYCARA' ,'DG4D' ,'AR28' ,'SATYA' ,'MITCHELL' ,'RR0S' ,'MV10' ,'CALLAN'
,'STIDLE' ,'WAIBEL' ,'WACTLAR' ,'SEF' ,'STENTZ' ,'KANADE' ,'DS1P' ,'JC6O' ,'WS1J'
,'MD3S' ,'RR6D' ,'WEHRER' ,'AS11' ,'JOHNA' ,'VSA' ,'BATAVIA' ,'DAN' ,'JACOBO'
,'CARROLL2' ,'COCHRAN' ,'EC15' ,'COPETAS' ,'RJC' ,'DE0U' ,'BILL' ,'JE0K' ,'DE66'
,'EVENSON' ,'FARBER' ,'FIENBERG' ,'FREDKIN' ,'MHAPPOLD' ,'HEFLEY' ,'TLH' ,'IKEUCHI' ,'PAMELAJ'
,'GKESDEN' ,'MK6X' ,'JKUBICA' ,'JKUKAWA' ,'SM38' ,'JOEMERTZ' ,'BASSOON' ,'TNG' ,'PATTIS'
,'PLAUT' ,'JR2U' ,'ROSSO' ,'SCERRI' ,'SCHANK' ,'SCHEINES' ,'TS1S' ,'SHAMOS' ,'JIANBOS'
,'MSITTI' ,'JS6W' ,'DSLATER' ,'DSA0' ,'MJS' ,'RS9F' ,'TYGAR' ,'AV0M'
)
/
spool off
