CONNECT / AS SYSDBA

CREATE ROLE "BACKUP_ADMIN"  NOT IDENTIFIED;
CREATE ROLE "BACKUP_CHANGE"  NOT IDENTIFIED;
CREATE ROLE "COSTING_ADMIN"  NOT IDENTIFIED;
CREATE ROLE "COSTING_CHANGE"  NOT IDENTIFIED;
CREATE ROLE "COSTING_VIEW"  NOT IDENTIFIED;
CREATE ROLE "EQUIP_ADMIN"  NOT IDENTIFIED;
CREATE ROLE "EQUIP_CHANGE"  NOT IDENTIFIED;
CREATE ROLE "EQUIP_VIEW"  NOT IDENTIFIED;
CREATE ROLE "EQUIP_WIZARD"  NOT IDENTIFIED;
CREATE ROLE "MAD_VIEW"  NOT IDENTIFIED;
CREATE ROLE "MAD_CHANGE"  NOT IDENTIFIED;
CREATE ROLE "NET_VIEW"  NOT IDENTIFIED;
CREATE ROLE "NET_CHANGE"  NOT IDENTIFIED;
CREATE ROLE "PURCH_QUERY"  NOT IDENTIFIED;
CREATE ROLE "PURCH_UPDATE"  NOT IDENTIFIED;
CREATE ROLE "PURCH_VIEW"  NOT IDENTIFIED;
CREATE ROLE "WEB_VIEW"  NOT IDENTIFIED;
CREATE ROLE "WEB_ACL_VIEW"  NOT IDENTIFIED;

commit;
quit;
