CREATE TABLE "HOSTDB"."EMP" 
(
	"EMP_NAME"	VARCHAR2(50 byte)
		NOT NULL
	, "FIRST"	VARCHAR2(50 byte)
	, "MIDDLE"	VARCHAR2(50 byte)
	, "LAST"	VARCHAR2(50 byte)
	, "SSN"		NUMBER(9)
	, "EMP_NUM"	NUMBER(7)
	, "CREATION_DATE"	DATE
	, "CREATED_BY"	VARCHAR2(30 byte)
	, "LAST_UPDATE"	DATE
	, "LAST_UPDATE_BY"	VARCHAR2(30 byte)
	, "ANDREW_ID" VARCHAR2(100 byte)
)  
    TABLESPACE "APPS"
    LOGGING 
/
