grant DELETE on HOSTDB.EMP to "COSTING_CHANGE";
grant INSERT on HOSTDB.EMP to "COSTING_CHANGE";
grant SELECT on HOSTDB.EMP to "COSTING_CHANGE";
grant UPDATE on HOSTDB.EMP to "COSTING_CHANGE";
grant SELECT on HOSTDB.EMP to "WEB_VIEW";
grant SELECT on HOSTDB.EMP to "AUD";
